// file:///Users/bentoblitzz/Documents/Playground/svenska_ovning/content/en/grammatik/substantiv/subskonjugation/subs_A1A2/alla_subs_konA1A2/alla_subs_konA1A2_data.js

// Here's the table header: | Article [input_hint] | SingularOb [hint] | SingularBe [input] | PluralOb [input] | PluralBe [input] | Group [group] | Translation [translation] |


const alla_subs_konA1A2_Data = [
    // Group 1: -or (mostly 'en' words ending in -a)
    { "article": "en", "singularOb": "anteckning", "singularBe": "anteckningen", "pluralOb": "anteckningar", "pluralBe": "anteckningarna", "group": "2", "translation": "note" },
    { "article": "en", "singularOb": "apelsin", "singularBe": "apelsinen", "pluralOb": "apelsiner", "pluralBe": "apelsinerna", "group": "3", "translation": "orange" },
    { "article": "en", "singularOb": "app", "singularBe": "appen", "pluralOb": "appar", "pluralBe": "apparna", "group": "2", "translation": "app" },
    { "article": "en", "singularOb": "årstid", "singularBe": "årstiden", "pluralOb": "årstider", "pluralBe": "årstiderna", "group": "3", "translation": "season" },
    { "article": "en", "singularOb": "åsikt", "singularBe": "åsikten", "pluralOb": "åsikter", "pluralBe": "åsikterna", "group": "3", "translation": "opinion" },
    { "article": "en", "singularOb": "åska", "singularBe": "åskan", "pluralOb": "-", "pluralBe": "-", "group": "1", "translation": "thunder" },
    { "article": "en", "singularOb": "avgift", "singularBe": "avgiften", "pluralOb": "avgifter", "pluralBe": "avgifterna", "group": "3", "translation": "fee" },
    { "article": "en", "singularOb": "avslutning", "singularBe": "avslutningen", "pluralOb": "avslutningar", "pluralBe": "avslutningarna", "group": "2", "translation": "ending/graduation" },
    { "article": "en", "singularOb": "balkong", "singularBe": "balkongen", "pluralOb": "balkonger", "pluralBe": "balkongerna", "group": "3", "translation": "balcony" },
    { "article": "en", "singularOb": "banan", "singularBe": "bananen", "pluralOb": "bananer", "pluralBe": "bananerna", "group": "3", "translation": "banana" },
    { "article": "en", "singularOb": "bil", "singularBe": "bilen", "pluralOb": "bilar", "pluralBe": "bilarna", "group": "2", "translation": "car" },
    { "article": "en", "singularOb": "bild", "singularBe": "bilden", "pluralOb": "bilder", "pluralBe": "bilderna", "group": "3", "translation": "picture" },
    { "article": "en", "singularOb": "blus", "singularBe": "blusen", "pluralOb": "blusar", "pluralBe": "blusarna", "group": "2", "translation": "blouse" },
    { "article": "en", "singularOb": "bok", "singularBe": "boken", "pluralOb": "böcker", "pluralBe": "böckerna", "group": "3 (irr)", "translation": "book" },
    { "article": "en", "singularOb": "bokhylla", "singularBe": "bokhyllan", "pluralOb": "bokhyllor", "pluralBe": "bokhyllorna", "group": "1", "translation": "bookshelf" },
    { "article": "en", "singularOb": "bostad", "singularBe": "bostaden", "pluralOb": "bostäder", "pluralBe": "bostäderna", "group": "3 (irr)", "translation": "residence" },
    { "article": "en", "singularOb": "bror", "singularBe": "brodern", "pluralOb": "bröder", "pluralBe": "bröderna", "group": "3 (irr)", "translation": "brother" },
    { "article": "en", "singularOb": "buss", "singularBe": "bussen", "pluralOb": "bussar", "pluralBe": "bussarna", "group": "2", "translation": "bus" },
    { "article": "en", "singularOb": "busshållplats", "singularBe": "busshållplatsen", "pluralOb": "busshållplatser", "pluralBe": "busshållplatserna", "group": "3", "translation": "bus stop" },
    { "article": "en", "singularOb": "butik", "singularBe": "butiken", "pluralOb": "butiker", "pluralBe": "butikerna", "group": "3", "translation": "shop" },
    { "article": "en", "singularOb": "byggnad", "singularBe": "byggnaden", "pluralOb": "byggnader", "pluralBe": "byggnaderna", "group": "3", "translation": "building" },
    { "article": "en", "singularOb": "byrå", "singularBe": "byrån", "pluralOb": "byråer", "pluralBe": "byråerna", "group": "3", "translation": "dresser/agency" },
    { "article": "en", "singularOb": "byxa", "singularBe": "byxan", "pluralOb": "byxor", "pluralBe": "byxorerna", "group": "1", "translation": "trousers/pants" },
    { "article": "en", "singularOb": "chef", "singularBe": "chefen", "pluralOb": "chefer", "pluralBe": "cheferna", "group": "3", "translation": "boss" },
    { "article": "en", "singularOb": "citron", "singularBe": "citronen", "pluralOb": "citroner", "pluralBe": "citronerna", "group": "3", "translation": "lemon" },
    { "article": "en", "singularOb": "cykel", "singularBe": "cykeln", "pluralOb": "cyklar", "pluralBe": "cyklarna", "group": "2", "translation": "bicycle" },
    { "article": "en", "singularOb": "dag", "singularBe": "dagen", "pluralOb": "dagar", "pluralBe": "dagarna", "group": "2", "translation": "day" },
    { "article": "en", "singularOb": "dammtrasa", "singularBe": "dammtrasan", "pluralOb": "dammtrasor", "pluralBe": "dammtrasorna", "group": "1", "translation": "dust cloth" },
    { "article": "en", "singularOb": "del", "singularBe": "delen", "pluralOb": "delar", "pluralBe": "delarna", "group": "2", "translation": "part" },
    { "article": "en", "singularOb": "dialog", "singularBe": "dialogen", "pluralOb": "dialoger", "pluralBe": "dialogerna", "group": "3", "translation": "dialogue" },
    { "article": "en", "singularOb": "dimma", "singularBe": "dimman", "pluralOb": "dimmor", "pluralBe": "dimmorna", "group": "1", "translation": "fog" },
    { "article": "en", "singularOb": "dotter", "singularBe": "dottern", "pluralOb": "döttrar", "pluralBe": "döttrarna", "group": "2 (irr)", "translation": "daughter" },
    { "article": "en", "singularOb": "eftermiddag", "singularBe": "eftermiddagen", "pluralOb": "eftermiddagar", "pluralBe": "eftermiddagarna", "group": "2", "translation": "afternoon" },
    { "article": "en", "singularOb": "elev", "singularBe": "eleven", "pluralOb": "elever", "pluralBe": "eleverna", "group": "3", "translation": "student" },
    { "article": "en", "singularOb": "enkät", "singularBe": "enkäten", "pluralOb": "enkäter", "pluralBe": "enkäterna", "group": "3", "translation": "survey" },
    { "article": "en", "singularOb": "erfarenhet", "singularBe": "erfarenheten", "pluralOb": "erfarenheter", "pluralBe": "erfarenheterna", "group": "3", "translation": "experience" },
    { "article": "en", "singularOb": "etta", "singularBe": "ettan", "pluralOb": "ettor", "pluralBe": "ettorna", "group": "1", "translation": "one-room apartment" },
    { "article": "en", "singularOb": "faktura", "singularBe": "fakturan", "pluralOb": "fakturor", "pluralBe": "fakturorna", "group": "1", "translation": "invoice" },
    { "article": "en", "singularOb": "familj", "singularBe": "familjen", "pluralOb": "familjer", "pluralBe": "familjerna", "group": "3", "translation": "family" },
    { "article": "en", "singularOb": "färg", "singularBe": "färgen", "pluralOb": "färger", "pluralBe": "färgerna", "group": "3", "translation": "color" },
    { "article": "en", "singularOb": "färja", "singularBe": "färjan", "pluralOb": "färjor", "pluralBe": "färjorna", "group": "1", "translation": "ferry" },
    { "article": "en", "singularOb": "fästman", "singularBe": "fästmannen", "pluralOb": "fästmän", "pluralBe": "fästmännen", "group": "5 (irr)", "translation": "fiancé (male)" },
    { "article": "en", "singularOb": "fästmö", "singularBe": "fästmön", "pluralOb": "fästmöar", "pluralBe": "fästmöarna", "group": "2", "translation": "fiancée (female)" },
    { "article": "en", "singularOb": "fåtölj", "singularBe": "fåtöljen", "pluralOb": "fåtöljer", "pluralBe": "fåtöljerna", "group": "3", "translation": "armchair" },
    { "article": "en", "singularOb": "fest", "singularBe": "festen", "pluralOb": "fester", "pluralBe": "festerna", "group": "3", "translation": "party" },
    { "article": "en", "singularOb": "festival", "singularBe": "festivalen", "pluralOb": "festivaler", "pluralBe": "festivalerna", "group": "3", "translation": "festival" },
    { "article": "en", "singularOb": "film", "singularBe": "filmen", "pluralOb": "filmer", "pluralBe": "filmerna", "group": "3", "translation": "movie" },
    { "article": "en", "singularOb": "fisk", "singularBe": "fisken", "pluralOb": "fiskar", "pluralBe": "fiskarna", "group": "2", "translation": "fish" },
    { "article": "en", "singularOb": "fläkt", "singularBe": "fläkten", "pluralOb": "fläktar", "pluralBe": "fläktarna", "group": "2", "translation": "fan" },
    { "article": "en", "singularOb": "flickvän", "singularBe": "flickvännen", "pluralOb": "flickvänner", "pluralBe": "flickvännerna", "group": "3", "translation": "girlfriend" },
    { "article": "en", "singularOb": "födelsedag", "singularBe": "födelsedagen", "pluralOb": "födelsedagar", "pluralBe": "födelsedagarna", "group": "2", "translation": "birthday" },
    { "article": "en", "singularOb": "fördel", "singularBe": "fördelen", "pluralOb": "fördelar", "pluralBe": "fördelarna", "group": "2", "translation": "advantage" },
    { "article": "en", "singularOb": "förening", "singularBe": "föreningen", "pluralOb": "föreningar", "pluralBe": "föreningarna", "group": "2", "translation": "association" },
    { "article": "en", "singularOb": "förmåga", "singularBe": "förmågan", "pluralOb": "förmågor", "pluralBe": "förmågorna", "group": "1", "translation": "ability" },
    { "article": "en", "singularOb": "förmiddag", "singularBe": "förmiddagen", "pluralOb": "förmiddagar", "pluralBe": "förmiddagarna", "group": "2", "translation": "morning (before noon)" },
    { "article": "en", "singularOb": "förort", "singularBe": "förorten", "pluralOb": "förorter", "pluralBe": "förorterna", "group": "3", "translation": "suburb" },
    { "article": "en", "singularOb": "förskola", "singularBe": "förskolan", "pluralOb": "förskolor", "pluralBe": "förskolorna", "group": "1", "translation": "preschool" },
    { "article": "en", "singularOb": "frisör", "singularBe": "frisören", "pluralOb": "frisörer", "pluralBe": "frisörerna", "group": "3", "translation": "hairdresser" },
    { "article": "en", "singularOb": "frukost", "singularBe": "frukosten", "pluralOb": "frukostar", "pluralBe": "frukostarna", "group": "2", "translation": "breakfast" },
    { "article": "en", "singularOb": "frys", "singularBe": "frysen", "pluralOb": "frysar", "pluralBe": "frysarna", "group": "2", "translation": "freezer" },
    { "article": "en", "singularOb": "gaffel", "singularBe": "gaffeln", "pluralOb": "gafflar", "pluralBe": "gafflarna", "group": "2", "translation": "fork" },
    { "article": "en", "singularOb": "gång", "singularBe": "gången", "pluralOb": "gånger", "pluralBe": "gångerna", "group": "3", "translation": "time/occurrence" },
    { "article": "en", "singularOb": "garanti", "singularBe": "garantin", "pluralOb": "garantier", "pluralBe": "garantierna", "group": "3", "translation": "warranty" },
    { "article": "en", "singularOb": "garderob", "singularBe": "garderoben", "pluralOb": "garderober", "pluralBe": "garderoberna", "group": "3", "translation": "wardrobe" },
    { "article": "en", "singularOb": "gardin", "singularBe": "gardinen", "pluralOb": "gardiner", "pluralBe": "gardinerna", "group": "3", "translation": "curtain" },
    { "article": "en", "singularOb": "gäst", "singularBe": "gästen", "pluralOb": "gäster", "pluralBe": "gästerna", "group": "3", "translation": "guest" },
    { "article": "en", "singularOb": "gata", "singularBe": "gatan", "pluralOb": "gator", "pluralBe": "gatorna", "group": "1", "translation": "street" },
    { "article": "en", "singularOb": "glögg", "singularBe": "glöggen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "mulled wine" },
    { "article": "en", "singularOb": "golvlampa", "singularBe": "golvlampan", "pluralOb": "golvlampor", "pluralBe": "golvlamporna", "group": "1", "translation": "floor lamp" },
    { "article": "en", "singularOb": "grad", "singularBe": "graden", "pluralOb": "grader", "pluralBe": "graderna", "group": "3", "translation": "degree" },
    { "article": "en", "singularOb": "granne", "singularBe": "grannen", "pluralOb": "grannar", "pluralBe": "grannarna", "group": "2", "translation": "neighbor" },
    { "article": "en", "singularOb": "grej", "singularBe": "grejen", "pluralOb": "grejer", "pluralBe": "grejerna", "group": "3", "translation": "thing" },
    { "article": "en", "singularOb": "grönsak", "singularBe": "grönsaken", "pluralOb": "grönsaker", "pluralBe": "grönsakerna", "group": "3", "translation": "vegetable" },
    { "article": "en", "singularOb": "grupp", "singularBe": "gruppen", "pluralOb": "grupper", "pluralBe": "grupperna", "group": "3", "translation": "group" },
    { "article": "en", "singularOb": "gryta", "singularBe": "grytan", "pluralOb": "grytor", "pluralBe": "grytorna", "group": "1", "translation": "stew/pot" },
    { "article": "en", "singularOb": "gurka", "singularBe": "gurkan", "pluralOb": "gurkor", "pluralBe": "gurkorna", "group": "1", "translation": "cucumber" },
    { "article": "en", "singularOb": "hall", "singularBe": "hallen", "pluralOb": "hallar", "pluralBe": "hallarna", "group": "2", "translation": "hallway" },
    { "article": "en", "singularOb": "hållplats", "singularBe": "hållplatsen", "pluralOb": "hållplatser", "pluralBe": "hållplatserna", "group": "3", "translation": "stop (bus/tram)" },
    { "article": "en", "singularOb": "hälsningsfras", "singularBe": "hälsningsfrasen", "pluralOb": "hälsningsfraser", "pluralBe": "hälsningsfraserna", "group": "3", "translation": "greeting phrase" },
    { "article": "en", "singularOb": "helg", "singularBe": "helgen", "pluralOb": "helger", "pluralBe": "helgerna", "group": "3", "translation": "weekend" },
    { "article": "en", "singularOb": "helhet", "singularBe": "helheten", "pluralOb": "helheter", "pluralBe": "helheterna", "group": "3", "translation": "totality/whole" },
    { "article": "en", "singularOb": "hink", "singularBe": "hinken", "pluralOb": "hinkar", "pluralBe": "hinkarna", "group": "2", "translation": "bucket" },
    { "article": "en", "singularOb": "hobby", "singularBe": "hobbyn", "pluralOb": "hobbier", "pluralBe": "hobbierna", "group": "3", "translation": "hobby" },
    { "article": "en", "singularOb": "hörövning", "singularBe": "hörövningen", "pluralOb": "hörövningar", "pluralBe": "hörövningarna", "group": "2", "translation": "listening exercise" },
    { "article": "en", "singularOb": "höst", "singularBe": "hösten", "pluralOb": "höstar", "pluralBe": "höstarna", "group": "2", "translation": "autumn" },
    { "article": "en", "singularOb": "hund", "singularBe": "hunden", "pluralOb": "hundar", "pluralBe": "hundarna", "group": "2", "translation": "dog" },
    { "article": "en", "singularOb": "hyra", "singularBe": "hyran", "pluralOb": "hyror", "pluralBe": "hyrorna", "group": "1", "translation": "rent" },
    { "article": "en", "singularOb": "hyresrätt", "singularBe": "hyresrätten", "pluralOb": "hyresrätter", "pluralBe": "hyresrätterna", "group": "3", "translation": "rental apartment" },
    { "article": "en", "singularOb": "hyresvärd", "singularBe": "hyresvärden", "pluralOb": "hyresvärdar", "pluralBe": "hyresvärdarna", "group": "2", "translation": "landlord" },
    { "article": "en", "singularOb": "ingenjör", "singularBe": "ingenjören", "pluralOb": "ingenjörer", "pluralBe": "ingenjörerna", "group": "3", "translation": "engineer" },
    { "article": "en", "singularOb": "ingrediens", "singularBe": "ingrediensen", "pluralOb": "ingredienser", "pluralBe": "ingredienserna", "group": "3", "translation": "ingredient" },
    { "article": "en", "singularOb": "inköpslista", "singularBe": "inköpslistan", "pluralOb": "inköpslistor", "pluralBe": "inköpslistorna", "group": "1", "translation": "shopping list" },
    { "article": "en", "singularOb": "inledning", "singularBe": "inledningen", "pluralOb": "inledningar", "pluralBe": "inledningarna", "group": "2", "translation": "introduction" },
    { "article": "en", "singularOb": "instruktion", "singularBe": "instruktionen", "pluralOb": "instruktioner", "pluralBe": "instruktionerna", "group": "3", "translation": "instruction" },
    { "article": "en", "singularOb": "jacka", "singularBe": "jackan", "pluralOb": "jackor", "pluralBe": "jackorna", "group": "1", "translation": "jacket" },
    { "article": "en", "singularOb": "jordgubbe", "singularBe": "jordgubben", "pluralOb": "jordgubbar", "pluralBe": "jordgubbarna", "group": "2", "translation": "strawberry" },
    { "article": "en", "singularOb": "juice", "singularBe": "juicen", "pluralOb": "juicer", "pluralBe": "juicerna", "group": "3", "translation": "juice" },
    { "article": "en", "singularOb": "julafton", "singularBe": "julaftonen", "pluralOb": "julaftnar", "pluralBe": "julaftnarna", "group": "2", "translation": "Christmas Eve" },
    { "article": "en", "singularOb": "kakelugn", "singularBe": "kakelugnen", "pluralOb": "kakelugnar", "pluralBe": "kakelugnarna", "group": "2", "translation": "tiled stove" },
    { "article": "en", "singularOb": "källare", "singularBe": "källaren", "pluralOb": "källare", "pluralBe": "källarna", "group": "5", "translation": "basement" },
    { "article": "en", "singularOb": "kampanj", "singularBe": "kampanjen", "pluralOb": "kampanjer", "pluralBe": "kampanjerna", "group": "3", "translation": "campaign" },
    { "article": "en", "singularOb": "kanelbulle", "singularBe": "kanelbullen", "pluralOb": "kanelbullar", "pluralBe": "kanelbullarna", "group": "2", "translation": "cinnamon bun" },
    { "article": "en", "singularOb": "kantarell", "singularBe": "kantarellen", "pluralOb": "kantareller", "pluralBe": "kantarellerna", "group": "3", "translation": "chanterelle" },
    { "article": "en", "singularOb": "kardemummabulle", "singularBe": "kardemummabullen", "pluralOb": "kardemummabullar", "pluralBe": "kardemummabullarna", "group": "2", "translation": "cardamom bun" },
    { "article": "en", "singularOb": "karta", "singularBe": "kartan", "pluralOb": "kartor", "pluralBe": "kartorna", "group": "1", "translation": "map" },
    { "article": "en", "singularOb": "kassa", "singularBe": "kassan", "pluralOb": "kassor", "pluralBe": "kassorna", "group": "1", "translation": "cashier/checkout" },
    { "article": "en", "singularOb": "kasse", "singularBe": "kassen", "pluralOb": "kassar", "pluralBe": "kassarna", "group": "2", "translation": "bag" },
    { "article": "en", "singularOb": "kassör", "singularBe": "kassören", "pluralOb": "kassörer", "pluralBe": "kassörerna", "group": "3", "translation": "cashier (person)" },
    { "article": "en", "singularOb": "kastrull", "singularBe": "kastrullen", "pluralOb": "kastruller", "pluralBe": "kastrullerna", "group": "3", "translation": "saucepan" },
    { "article": "en", "singularOb": "klänning", "singularBe": "klänningen", "pluralOb": "klänningar", "pluralBe": "klänningarna", "group": "2", "translation": "dress" },
    { "article": "en", "singularOb": "klocka", "singularBe": "klockan", "pluralOb": "klockor", "pluralBe": "klockorna", "group": "1", "translation": "clock/watch" },
    { "article": "en", "singularOb": "kniv", "singularBe": "kniven", "pluralOb": "knivar", "pluralBe": "knivarna", "group": "2", "translation": "knife" },
    { "article": "en", "singularOb": "kö", "singularBe": "kön", "pluralOb": "köer", "pluralBe": "köerna", "group": "3", "translation": "queue/line" },
    { "article": "en", "singularOb": "kock", "singularBe": "kocken", "pluralOb": "kockar", "pluralBe": "kockarna", "group": "2", "translation": "cook/chef" },
    { "article": "en", "singularOb": "kofta", "singularBe": "koftan", "pluralOb": "koftor", "pluralBe": "koftorna", "group": "1", "translation": "cardigan" },
    { "article": "en", "singularOb": "kollega", "singularBe": "kollegan", "pluralOb": "kollegor", "pluralBe": "kollegorna", "group": "1", "translation": "colleague" },
    { "article": "en", "singularOb": "kompis", "singularBe": "kompisen", "pluralOb": "kompisar", "pluralBe": "kompisarna", "group": "2", "translation": "friend" },
    { "article": "en", "singularOb": "konsert", "singularBe": "konserten", "pluralOb": "konserter", "pluralBe": "konserterna", "group": "3", "translation": "concert" },
    { "article": "en", "singularOb": "konstnär", "singularBe": "konstnären", "pluralOb": "konstnärer", "pluralBe": "konstnärerna", "group": "3", "translation": "artist" },
    { "article": "en", "singularOb": "kopp", "singularBe": "koppen", "pluralOb": "koppar", "pluralBe": "kopparna", "group": "2", "translation": "cup" },
    { "article": "en", "singularOb": "koppling", "singularBe": "kopplingen", "pluralOb": "kopplingar", "pluralBe": "kopplingarna", "group": "2", "translation": "connection" },
    { "article": "en", "singularOb": "kostnad", "singularBe": "kostnaden", "pluralOb": "kostnader", "pluralBe": "kostnaderna", "group": "3", "translation": "cost" },
    { "article": "en", "singularOb": "kostym", "singularBe": "kostymen", "pluralOb": "kostymer", "pluralBe": "kostymerna", "group": "3", "translation": "suit" },
    { "article": "en", "singularOb": "kostymbyxa", "singularBe": "kostymbyxan", "pluralOb": "kostymbyxor", "pluralBe": "kostymbyxorerna", "group": "1", "translation": "suit pants" },
    { "article": "en", "singularOb": "köttfärs", "singularBe": "köttfärsen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "minced meat" },
    { "article": "en", "singularOb": "krukväxt", "singularBe": "krukväxten", "pluralOb": "krukväxter", "pluralBe": "krukväxterna", "group": "3", "translation": "potted plant" },
    { "article": "en", "singularOb": "kudde", "singularBe": "kudden", "pluralOb": "kuddar", "pluralBe": "kuddarna", "group": "2", "translation": "pillow" },
    { "article": "en", "singularOb": "kund", "singularBe": "kunden", "pluralOb": "kunder", "pluralBe": "kunderna", "group": "3", "translation": "customer" },
    { "article": "en", "singularOb": "kusin", "singularBe": "kusinen", "pluralOb": "kusiner", "pluralBe": "kusinerna", "group": "3", "translation": "cousin" },
    { "article": "en", "singularOb": "kvadratmeter", "singularBe": "kvadratmetern", "pluralOb": "kvadratmeter", "pluralBe": "kvadratmetrarna", "group": "5", "translation": "square meter" },
    { "article": "en", "singularOb": "kvalitet", "singularBe": "kvaliteten", "pluralOb": "kvaliteter", "pluralBe": "kvaliteterna", "group": "3", "translation": "quality" },
    { "article": "en", "singularOb": "kväll", "singularBe": "kvällen", "pluralOb": "kvällar", "pluralBe": "kvällarna", "group": "2", "translation": "evening" },
    { "article": "en", "singularOb": "kvart", "singularBe": "kvarten", "pluralOb": "kvartar", "pluralBe": "kvartarna", "group": "2", "translation": "quarter (time)" },
    { "article": "en", "singularOb": "kyrka", "singularBe": "kyrkan", "pluralOb": "kyrkor", "pluralBe": "kyrkorna", "group": "1", "translation": "church" },
    { "article": "en", "singularOb": "lägenhet", "singularBe": "lägenheten", "pluralOb": "lägenheter", "pluralBe": "lägenheterna", "group": "3", "translation": "apartment" },
    { "article": "en", "singularOb": "läkare", "singularBe": "läkaren", "pluralOb": "läkare", "pluralBe": "läkarna", "group": "5", "translation": "doctor" },
    { "article": "en", "singularOb": "lampa", "singularBe": "lampan", "pluralOb": "lampor", "pluralBe": "lamporna", "group": "1", "translation": "lamp" },
    { "article": "en", "singularOb": "lax", "singularBe": "laxen", "pluralOb": "laxar", "pluralBe": "laxarna", "group": "2", "translation": "salmon" },
    { "article": "en", "singularOb": "läxa", "singularBe": "läxan", "pluralOb": "läxor", "pluralBe": "läxorna", "group": "1", "translation": "homework" },
    { "article": "en", "singularOb": "lekplats", "singularBe": "lekplatsen", "pluralOb": "lekplatser", "pluralBe": "lekplatserna", "group": "3", "translation": "playground" },
    { "article": "en", "singularOb": "lektion", "singularBe": "lektionen", "pluralOb": "lektioner", "pluralBe": "lektionerna", "group": "3", "translation": "lesson" },
    { "article": "en", "singularOb": "ljudbok", "singularBe": "ljudboken", "pluralOb": "ljudböcker", "pluralBe": "ljudböckerna", "group": "3 (irr)", "translation": "audiobook" },
    { "article": "en", "singularOb": "lön", "singularBe": "lönen", "pluralOb": "löner", "pluralBe": "lönerna", "group": "3", "translation": "salary" },
    { "article": "en", "singularOb": "lördag", "singularBe": "lördagen", "pluralOb": "lördagar", "pluralBe": "lördagarna", "group": "2", "translation": "Saturday" },
    { "article": "en", "singularOb": "lunch", "singularBe": "lunchen", "pluralOb": "luncher", "pluralBe": "luncherna", "group": "3", "translation": "lunch" },
    { "article": "en", "singularOb": "mack", "singularBe": "macken", "pluralOb": "mackar", "pluralBe": "mackarna", "group": "2", "translation": "gas station" },
    { "article": "en", "singularOb": "macka", "singularBe": "mackan", "pluralOb": "mackor", "pluralBe": "mackorna", "group": "1", "translation": "sandwich" },
    { "article": "en", "singularOb": "madrass", "singularBe": "madrassen", "pluralOb": "madrasser", "pluralBe": "madrasserna", "group": "3", "translation": "mattress" },
    { "article": "en", "singularOb": "mamma", "singularBe": "mamman", "pluralOb": "mammor", "pluralBe": "mammorna", "group": "1", "translation": "mom" },
    { "article": "en", "singularOb": "man", "singularBe": "mannen", "pluralOb": "män", "pluralBe": "männen", "group": "5 (irr)", "translation": "man" },
    { "article": "en", "singularOb": "månad", "singularBe": "månaden", "pluralOb": "månader", "pluralBe": "månaderna", "group": "3", "translation": "month" },
    { "article": "en", "singularOb": "människa", "singularBe": "människan", "pluralOb": "människor", "pluralBe": "människorna", "group": "1", "translation": "human" },
    { "article": "en", "singularOb": "marknad", "singularBe": "marknaden", "pluralOb": "marknader", "pluralBe": "marknaderna", "group": "3", "translation": "market" },
    { "article": "en", "singularOb": "maskin", "singularBe": "maskinen", "pluralOb": "maskiner", "pluralBe": "maskinerna", "group": "3", "translation": "machine" },
    { "article": "en", "singularOb": "matbutik", "singularBe": "matbutiken", "pluralOb": "matbutiker", "pluralBe": "matbutikerna", "group": "3", "translation": "grocery store" },
    { "article": "en", "singularOb": "maträtt", "singularBe": "maträtten", "pluralOb": "maträtter", "pluralBe": "maträtterna", "group": "3", "translation": "dish (food)" },
    { "article": "en", "singularOb": "matta", "singularBe": "mattan", "pluralOb": "mattor", "pluralBe": "mattorna", "group": "1", "translation": "carpet" },
    { "article": "en", "singularOb": "medlem", "singularBe": "medlemmen", "pluralOb": "medlemmar", "pluralBe": "medlemmarna", "group": "2", "translation": "member" },
    { "article": "en", "singularOb": "middag", "singularBe": "middagen", "pluralOb": "middagar", "pluralBe": "middagarna", "group": "2", "translation": "dinner" },
    { "article": "en", "singularOb": "mikrovågsugn", "singularBe": "mikrovågsugnen", "pluralOb": "mikrovågsugnar", "pluralBe": "mikrovågsugnarna", "group": "2", "translation": "microwave" },
    { "article": "en", "singularOb": "minut", "singularBe": "minuten", "pluralOb": "minuter", "pluralBe": "minuterna", "group": "3", "translation": "minute" },
    { "article": "en", "singularOb": "mobil", "singularBe": "mobilen", "pluralOb": "mobiler", "pluralBe": "mobilerna", "group": "3", "translation": "mobile phone" },
    { "article": "en", "singularOb": "möjlighet", "singularBe": "möjligheten", "pluralOb": "möjligheter", "pluralBe": "möjligheterna", "group": "3", "translation": "possibility" },
    { "article": "en", "singularOb": "morgon", "singularBe": "morgonen", "pluralOb": "morgnar", "pluralBe": "morgnarna", "group": "2", "translation": "morning" },
    { "article": "en", "singularOb": "moster", "singularBe": "mostern", "pluralOb": "mostrar", "pluralBe": "mostrarna", "group": "2", "translation": "aunt (maternal)" },
    { "article": "en", "singularOb": "motion", "singularBe": "motionen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "exercise" },
    { "article": "en", "singularOb": "motorväg", "singularBe": "motorvägen", "pluralOb": "motorvägar", "pluralBe": "motorvägarna", "group": "2", "translation": "highway" },
    { "article": "en", "singularOb": "musik", "singularBe": "musiken", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "music" },
    { "article": "en", "singularOb": "nackdel", "singularBe": "nackdelen", "pluralOb": "nackdelar", "pluralBe": "nackdelarna", "group": "2", "translation": "disadvantage" },
    { "article": "en", "singularOb": "nackspärr", "singularBe": "nackspärren", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "stiff neck" },
    { "article": "en", "singularOb": "natt", "singularBe": "natten", "pluralOb": "nätter", "pluralBe": "nätterna", "group": "3 (irr)", "translation": "night" },
    { "article": "en", "singularOb": "nyhet", "singularBe": "nyheten", "pluralOb": "nyheter", "pluralBe": "nyheterna", "group": "3", "translation": "news" },
    { "article": "en", "singularOb": "öken", "singularBe": "öknen", "pluralOb": "öknar", "pluralBe": "öknarna", "group": "2", "translation": "desert" },
    { "article": "en", "singularOb": "opera", "singularBe": "operan", "pluralOb": "operor", "pluralBe": "operorna", "group": "1", "translation": "opera" },
    { "article": "en", "singularOb": "öppen spis", "singularBe": "öppna spisen", "pluralOb": "öppna spisar", "pluralBe": "öppna spisarna", "group": "2", "translation": "fireplace" },
    { "article": "en", "singularOb": "ost", "singularBe": "osten", "pluralOb": "ostar", "pluralBe": "ostarna", "group": "2", "translation": "cheese" },
    { "article": "en", "singularOb": "övning", "singularBe": "övningen", "pluralOb": "övningar", "pluralBe": "övningarna", "group": "2", "translation": "exercise" },
    { "article": "en", "singularOb": "paj", "singularBe": "pajen", "pluralOb": "pajer", "pluralBe": "pajerna", "group": "3", "translation": "pie" },
    { "article": "en", "singularOb": "pall", "singularBe": "pallen", "pluralOb": "pallar", "pluralBe": "pallarna", "group": "2", "translation": "stool" },
    { "article": "en", "singularOb": "pannkaka", "singularBe": "pannkakan", "pluralOb": "pannkakor", "pluralBe": "pannkakorna", "group": "1", "translation": "pancake" },
    { "article": "en", "singularOb": "pappa", "singularBe": "pappan", "pluralOb": "pappor", "pluralBe": "papporna", "group": "1", "translation": "dad" },
    { "article": "en", "singularOb": "paprika", "singularBe": "paprikan", "pluralOb": "paprikor", "pluralBe": "paprikorna", "group": "1", "translation": "bell pepper" },
    { "article": "en", "singularOb": "park", "singularBe": "parken", "pluralOb": "parker", "pluralBe": "parkerna", "group": "3", "translation": "park" },
    { "article": "en", "singularOb": "partner", "singularBe": "partnern", "pluralOb": "partner", "pluralBe": "partnerna", "group": "5", "translation": "partner" },
    { "article": "en", "singularOb": "påse", "singularBe": "påsen", "pluralOb": "påsar", "pluralBe": "påsarna", "group": "2", "translation": "bag (small)" },
    { "article": "en", "singularOb": "penna", "singularBe": "pennan", "pluralOb": "pennor", "pluralBe": "pennorna", "group": "1", "translation": "pen" },
    { "article": "en", "singularOb": "person", "singularBe": "personen", "pluralOb": "personer", "pluralBe": "personerna", "group": "3", "translation": "person" },
    { "article": "en", "singularOb": "plan", "singularBe": "planen", "pluralOb": "planer", "pluralBe": "planerna", "group": "3", "translation": "plan" },
    { "article": "en", "singularOb": "planritning", "singularBe": "planritningen", "pluralOb": "planritningar", "pluralBe": "planritningarna", "group": "2", "translation": "floor plan" },
    { "article": "en", "singularOb": "podd", "singularBe": "podden", "pluralOb": "poddar", "pluralBe": "poddarna", "group": "2", "translation": "podcast" },
    { "article": "en", "singularOb": "present", "singularBe": "presenten", "pluralOb": "presenter", "pluralBe": "presenterna", "group": "3", "translation": "present" },
    { "article": "en", "singularOb": "presentation", "singularBe": "presentationen", "pluralOb": "presentationer", "pluralBe": "presentationerna", "group": "3", "translation": "presentation" },
    { "article": "en", "singularOb": "promenad", "singularBe": "promenaden", "pluralOb": "promenader", "pluralBe": "promenaderna", "group": "3", "translation": "walk" },
    { "article": "en", "singularOb": "purjolök", "singularBe": "purjolöken", "pluralOb": "purjolökar", "pluralBe": "purjolökarna", "group": "2", "translation": "leek" },
    { "article": "en", "singularOb": "rabatt", "singularBe": "rabatten", "pluralOb": "rabatter", "pluralBe": "rabatterna", "group": "3", "translation": "discount/flowerbed" },
    { "article": "en", "singularOb": "räkning", "singularBe": "räkningen", "pluralOb": "räkningar", "pluralBe": "räkningarna", "group": "2", "translation": "bill" },
    { "article": "en", "singularOb": "rea", "singularBe": "rean", "pluralOb": "reor", "pluralBe": "reorna", "group": "1", "translation": "sale" },
    { "article": "en", "singularOb": "recension", "singularBe": "recensionen", "pluralOb": "recensioner", "pluralBe": "recensionerna", "group": "3", "translation": "review" },
    { "article": "en", "singularOb": "reklam", "singularBe": "reklamen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "advertising" },
    { "article": "en", "singularOb": "relation", "singularBe": "relationen", "pluralOb": "relationer", "pluralBe": "relationerna", "group": "3", "translation": "relation" },
    { "article": "en", "singularOb": "resetid", "singularBe": "resetiden", "pluralOb": "resetider", "pluralBe": "resetiderna", "group": "3", "translation": "travel time" },
    { "article": "en", "singularOb": "restaurang", "singularBe": "restaurangen", "pluralOb": "restauranger", "pluralBe": "restaurangerna", "group": "3", "translation": "restaurant" },
    { "article": "en", "singularOb": "retur", "singularBe": "returen", "pluralOb": "returer", "pluralBe": "returerna", "group": "3", "translation": "return" },
    { "article": "en", "singularOb": "rock", "singularBe": "rocken", "pluralOb": "rockar", "pluralBe": "rockarna", "group": "2", "translation": "coat" },
    { "article": "en", "singularOb": "roman", "singularBe": "romanen", "pluralOb": "romaner", "pluralBe": "romanerna", "group": "3", "translation": "novel" },
    { "article": "en", "singularOb": "runda", "singularBe": "rundan", "pluralOb": "rundor", "pluralBe": "rundorna", "group": "1", "translation": "round/circuit" },
    { "article": "en", "singularOb": "rundresa", "singularBe": "rundresan", "pluralOb": "rundresor", "pluralBe": "rundresorna", "group": "1", "translation": "round trip" },
    { "article": "en", "singularOb": "rutin", "singularBe": "rutinen", "pluralOb": "rutiner", "pluralBe": "rutinerna", "group": "3", "translation": "routine" },
    { "article": "en", "singularOb": "sallad", "singularBe": "salladen", "pluralOb": "sallader", "pluralBe": "salladerna", "group": "3", "translation": "salad" },
    { "article": "en", "singularOb": "sambo", "singularBe": "sambon", "pluralOb": "sambor", "pluralBe": "samborna", "group": "1", "translation": "cohabitant" },
    { "article": "en", "singularOb": "sång", "singularBe": "sången", "pluralOb": "sånger", "pluralBe": "sångerna", "group": "3", "translation": "song" },
    { "article": "en", "singularOb": "säng", "singularBe": "sängen", "pluralOb": "sängar", "pluralBe": "sängarna", "group": "2", "translation": "bed" },
    { "article": "en", "singularOb": "sanning", "singularBe": "sanningen", "pluralOb": "sanningar", "pluralBe": "sanningarna", "group": "2", "translation": "truth" },
    { "article": "en", "singularOb": "särbo", "singularBe": "särbon", "pluralOb": "särbor", "pluralBe": "särborna", "group": "1", "translation": "partner (not living together)" },
    { "article": "en", "singularOb": "sedel", "singularBe": "sedeln", "pluralOb": "sedlar", "pluralBe": "sedlarna", "group": "2", "translation": "banknote" },
    { "article": "en", "singularOb": "sekund", "singularBe": "sekunden", "pluralOb": "sekunder", "pluralBe": "sekunderna", "group": "3", "translation": "second" },
    { "article": "en", "singularOb": "semester", "singularBe": "semestern", "pluralOb": "semestrar", "pluralBe": "semestrarna", "group": "2", "translation": "vacation" },
    { "article": "en", "singularOb": "semla", "singularBe": "semlan", "pluralOb": "semlor", "pluralBe": "semlorna", "group": "1", "translation": "semla (pastry)" },
    { "article": "en", "singularOb": "serie", "singularBe": "serien", "pluralOb": "serier", "pluralBe": "serierna", "group": "3", "translation": "series" },
    { "article": "en", "singularOb": "siffra", "singularBe": "siffran", "pluralOb": "siffror", "pluralBe": "siffrorna", "group": "1", "translation": "digit/figure" },
    { "article": "en", "singularOb": "sjal", "singularBe": "sjalen", "pluralOb": "sjalar", "pluralBe": "sjalarna", "group": "2", "translation": "scarf/shawl" },
    { "article": "en", "singularOb": "skål", "singularBe": "skålen", "pluralOb": "skålar", "pluralBe": "skålarna", "group": "2", "translation": "bowl" },
    { "article": "en", "singularOb": "skärgård", "singularBe": "skärgården", "pluralOb": "skärgårdar", "pluralBe": "skärgårdarna", "group": "2", "translation": "archipelago" },
    { "article": "en", "singularOb": "skatt", "singularBe": "skatten", "pluralOb": "skatter", "pluralBe": "skatterna", "group": "3", "translation": "tax" },
    { "article": "en", "singularOb": "sked", "singularBe": "skeden", "pluralOb": "skedar", "pluralBe": "skedarna", "group": "2", "translation": "spoon" },
    { "article": "en", "singularOb": "skillnad", "singularBe": "skillnaden", "pluralOb": "skillnader", "pluralBe": "skillnaderna", "group": "3", "translation": "difference" },
    { "article": "en", "singularOb": "skjorta", "singularBe": "skjortan", "pluralOb": "skjortor", "pluralBe": "skjortorna", "group": "1", "translation": "shirt" },
    { "article": "en", "singularOb": "sko", "singularBe": "skon", "pluralOb": "skor", "pluralBe": "skorna", "group": "3", "translation": "shoe" },
    { "article": "en", "singularOb": "skog", "singularBe": "skogen", "pluralOb": "skogar", "pluralBe": "skogarna", "group": "2", "translation": "forest" },
    { "article": "en", "singularOb": "skola", "singularBe": "skolan", "pluralOb": "skolor", "pluralBe": "skolorna", "group": "1", "translation": "school" },
    { "article": "en", "singularOb": "skurhink", "singularBe": "skurhinken", "pluralOb": "skurhinkar", "pluralBe": "skurhinkarna", "group": "2", "translation": "mop bucket" },
    { "article": "en", "singularOb": "skylt", "singularBe": "skylten", "pluralOb": "skyltar", "pluralBe": "skyltarna", "group": "2", "translation": "sign" },
    { "article": "en", "singularOb": "släkting", "singularBe": "släktingen", "pluralOb": "släktingar", "pluralBe": "släktingarna", "group": "2", "translation": "relative" },
    { "article": "en", "singularOb": "smörgås", "singularBe": "smörgåsen", "pluralOb": "smörgåsar", "pluralBe": "smörgåsarna", "group": "2", "translation": "sandwich" },
    { "article": "en", "singularOb": "soffa", "singularBe": "soffan", "pluralOb": "soffor", "pluralBe": "sofforna", "group": "1", "translation": "sofa" },
    { "article": "en", "singularOb": "sol", "singularBe": "solen", "pluralOb": "solar", "pluralBe": "solarna", "group": "2", "translation": "sun" },
    { "article": "en", "singularOb": "sommar", "singularBe": "sommaren", "pluralOb": "somrar", "pluralBe": "somrarna", "group": "2", "translation": "summer" },
    { "article": "en", "singularOb": "son", "singularBe": "sonen", "pluralOb": "söner", "pluralBe": "sönerna", "group": "3 (irr)", "translation": "son" },
    { "article": "en", "singularOb": "spegel", "singularBe": "spegeln", "pluralOb": "speglar", "pluralBe": "speglarna", "group": "2", "translation": "mirror" },
    { "article": "en", "singularOb": "spis", "singularBe": "spisen", "pluralOb": "spisar", "pluralBe": "spisarna", "group": "2", "translation": "stove" },
    { "article": "en", "singularOb": "stad", "singularBe": "staden", "pluralOb": "städer", "pluralBe": "städerna", "group": "3 (irr)", "translation": "city" },
    { "article": "en", "singularOb": "stadskärna", "singularBe": "stadskärnan", "pluralOb": "stadskärnor", "pluralBe": "stadskärnorna", "group": "1", "translation": "city center" },
    { "article": "en", "singularOb": "station", "singularBe": "stationen", "pluralOb": "stationer", "pluralBe": "stationerna", "group": "3", "translation": "station" },
    { "article": "en", "singularOb": "stavelse", "singularBe": "stavelsen", "pluralOb": "stavelser", "pluralBe": "stavelserna", "group": "3", "translation": "syllable" },
    { "article": "en", "singularOb": "stol", "singularBe": "stolen", "pluralOb": "stolar", "pluralBe": "stolarna", "group": "2", "translation": "chair" },
    { "article": "en", "singularOb": "strand", "singularBe": "stranden", "pluralOb": "stränder", "pluralBe": "stränderna", "group": "3 (irr)", "translation": "beach" },
    { "article": "en", "singularOb": "strumpa", "singularBe": "strumpan", "pluralOb": "strumpor", "pluralBe": "strumporna", "group": "1", "translation": "sock" },
    { "article": "en", "singularOb": "stuga", "singularBe": "stugan", "pluralOb": "stugor", "pluralBe": "stugorna", "group": "1", "translation": "cottage" },
    { "article": "en", "singularOb": "stund", "singularBe": "stunden", "pluralOb": "stunder", "pluralBe": "stunderna", "group": "3", "translation": "moment" },
    { "article": "en", "singularOb": "svåger", "singularBe": "svågern", "pluralOb": "svågrar", "pluralBe": "svågrarna", "group": "2", "translation": "brother-in-law" },
    { "article": "en", "singularOb": "svägerska", "singularBe": "svägerskan", "pluralOb": "svägerskor", "pluralBe": "svägerskorna", "group": "1", "translation": "sister-in-law" },
    { "article": "en", "singularOb": "svamp", "singularBe": "svampen", "pluralOb": "svampar", "pluralBe": "svamparna", "group": "2", "translation": "mushroom" },
    { "article": "en", "singularOb": "svärmor", "singularBe": "svärmodern", "pluralOb": "svärmödrar", "pluralBe": "svärmödrarna", "group": "2 (irr)", "translation": "mother-in-law" },
    { "article": "en", "singularOb": "syster", "singularBe": "systern", "pluralOb": "systrar", "pluralBe": "systrarna", "group": "2", "translation": "sister" },
    { "article": "en", "singularOb": "tabell", "singularBe": "tabellen", "pluralOb": "tabeller", "pluralBe": "tabellerna", "group": "3", "translation": "table/chart" },
    { "article": "en", "singularOb": "tallrik", "singularBe": "tallriken", "pluralOb": "tallrikar", "pluralBe": "tallrikarna", "group": "2", "translation": "plate" },
    { "article": "en", "singularOb": "tavla", "singularBe": "tavlan", "pluralOb": "tavlor", "pluralBe": "tavlorna", "group": "1", "translation": "painting/board" },
    { "article": "en", "singularOb": "taxi", "singularBe": "taxin", "pluralOb": "taxibilar", "pluralBe": "taxibilarna", "group": "2", "translation": "taxi" },
    { "article": "en", "singularOb": "teater", "singularBe": "teatern", "pluralOb": "teatrar", "pluralBe": "teatrarna", "group": "2", "translation": "theater" },
    { "article": "en", "singularOb": "timme", "singularBe": "timmen", "pluralOb": "timmar", "pluralBe": "timmarna", "group": "2", "translation": "hour" },
    { "article": "en", "singularOb": "tomat", "singularBe": "tomaten", "pluralOb": "tomater", "pluralBe": "tomaterna", "group": "3", "translation": "tomato" },
    { "article": "en", "singularOb": "tomt", "singularBe": "tomten", "pluralOb": "tomter", "pluralBe": "tomterna", "group": "3", "translation": "plot of land" },
    { "article": "en", "singularOb": "torkställning", "singularBe": "torkställningen", "pluralOb": "torkställningar", "pluralBe": "torkställningarna", "group": "2", "translation": "drying rack" },
    { "article": "en", "singularOb": "torktumlare", "singularBe": "torktumlaren", "pluralOb": "torktumlare", "pluralBe": "torktumlarna", "group": "5", "translation": "tumble dryer" },
    { "article": "en", "singularOb": "trädgård", "singularBe": "trädgården", "pluralOb": "trädgårdar", "pluralBe": "trädgårdarna", "group": "2", "translation": "garden" },
    { "article": "en", "singularOb": "trappa", "singularBe": "trappan", "pluralOb": "trappor", "pluralBe": "trapporna", "group": "1", "translation": "stairs" },
    { "article": "en", "singularOb": "trasa", "singularBe": "trasan", "pluralOb": "trasor", "pluralBe": "trasorna", "group": "1", "translation": "rag" },
    { "article": "en", "singularOb": "tröja", "singularBe": "tröjan", "pluralOb": "tröjor", "pluralBe": "tröjorna", "group": "1", "translation": "sweater" },
    { "article": "en", "singularOb": "tunnelbana", "singularBe": "tunnelbanan", "pluralOb": "tunnelbanor", "pluralBe": "tunnelbanorna", "group": "1", "translation": "subway" },
    { "article": "en", "singularOb": "turist", "singularBe": "turisten", "pluralOb": "turister", "pluralBe": "turisterna", "group": "3", "translation": "tourist" },
    { "article": "en", "singularOb": "tvåa", "singularBe": "tvåan", "pluralOb": "tvåor", "pluralBe": "tvåorna", "group": "1", "translation": "two-room apartment" },
    { "article": "en", "singularOb": "tvättstuga", "singularBe": "tvättstugan", "pluralOb": "tvättstugor", "pluralBe": "tvättstugorna", "group": "1", "translation": "laundry room" },
    { "article": "en", "singularOb": "ugn", "singularBe": "ugnen", "pluralOb": "ugnar", "pluralBe": "ugnarna", "group": "2", "translation": "oven" },
    { "article": "en", "singularOb": "undertext", "singularBe": "undertexten", "pluralOb": "undertexter", "pluralBe": "undertexterna", "group": "3", "translation": "subtitle" },
    { "article": "en", "singularOb": "uppgift", "singularBe": "uppgiften", "pluralOb": "uppgifter", "pluralBe": "uppgifterna", "group": "3", "translation": "task" },
    { "article": "en", "singularOb": "utflykt", "singularBe": "utflykten", "pluralOb": "utflykter", "pluralBe": "utflykterna", "group": "3", "translation": "excursion" },
    { "article": "en", "singularOb": "utgift", "singularBe": "utgiften", "pluralOb": "utgifter", "pluralBe": "utgifterna", "group": "3", "translation": "expense" },
    { "article": "en", "singularOb": "väderleksrapport", "singularBe": "väderleksrapporten", "pluralOb": "väderleksrapporter", "pluralBe": "väderleksrapporterna", "group": "3", "translation": "weather report" },
    { "article": "en", "singularOb": "vägbeskrivning", "singularBe": "vägbeskrivningen", "pluralOb": "vägbeskrivningar", "pluralBe": "vägbeskrivningarna", "group": "2", "translation": "directions" },
    { "article": "en", "singularOb": "vän", "singularBe": "vännen", "pluralOb": "vänner", "pluralBe": "vännerna", "group": "3", "translation": "friend" },
    { "article": "en", "singularOb": "vana", "singularBe": "vanan", "pluralOb": "vanor", "pluralBe": "vanorna", "group": "1", "translation": "habit" },
    { "article": "en", "singularOb": "vandring", "singularBe": "vandringen", "pluralOb": "vandringar", "pluralBe": "vandringarna", "group": "2", "translation": "hiking" },
    { "article": "en", "singularOb": "våning", "singularBe": "våningen", "pluralOb": "våningar", "pluralBe": "våningarna", "group": "2", "translation": "floor/apartment" },
    { "article": "en", "singularOb": "vardag", "singularBe": "vardagen", "pluralOb": "vardagar", "pluralBe": "vardagarna", "group": "2", "translation": "weekday" },
    { "article": "en", "singularOb": "vecka", "singularBe": "veckan", "pluralOb": "veckor", "pluralBe": "veckorna", "group": "1", "translation": "week" },
    { "article": "en", "singularOb": "version", "singularBe": "versionen", "pluralOb": "versioner", "pluralBe": "versionerna", "group": "3", "translation": "version" },
    { "article": "en", "singularOb": "vigsel", "singularBe": "vigseln", "pluralOb": "vigslar", "pluralBe": "vigslarna", "group": "2", "translation": "wedding ceremony" },
    { "article": "en", "singularOb": "villa", "singularBe": "villan", "pluralOb": "villor", "pluralBe": "villorna", "group": "1", "translation": "villa" },
    { "article": "en", "singularOb": "vind", "singularBe": "vinden", "pluralOb": "vindar", "pluralBe": "vindarna", "group": "2", "translation": "wind" },
    { "article": "en", "singularOb": "vindruva", "singularBe": "vindruvan", "pluralOb": "vindruvor", "pluralBe": "vindruvorna", "group": "1", "translation": "grape" },
    { "article": "en", "singularOb": "vinter", "singularBe": "vintern", "pluralOb": "vintrar", "pluralBe": "vintrarna", "group": "2", "translation": "winter" },
    { "article": "en", "singularOb": "visa", "singularBe": "visan", "pluralOb": "visor", "pluralBe": "visorna", "group": "1", "translation": "song/tune" },

    // Group 4: -n (ett words ending in vowel)
    { "article": "ett", "singularOb": "äpple", "singularBe": "äpplet", "pluralOb": "äpplen", "pluralBe": "äpplena", "group": "4", "translation": "apple" },
    { "article": "ett", "singularOb": "århundrade", "singularBe": "århundradet", "pluralOb": "århundraden", "pluralBe": "århundradena", "group": "4", "translation": "century" },
    { "article": "ett", "singularOb": "bageri", "singularBe": "bageriet", "pluralOb": "bagerier", "pluralBe": "bagerierna", "group": "3", "translation": "bakery" },
    { "article": "ett:a", "singularOb": "boarea", "singularBe": "boarean", "pluralOb": "boareor", "pluralBe": "boareorna", "group": "1", "translation": "living area" },
    { "article": "ett", "singularOb": "boende", "singularBe": "boendet", "pluralOb": "boenden", "pluralBe": "boendena", "group": "4", "translation": "housing" },
    { "article": "ett", "singularOb": "café", "singularBe": "caféet", "pluralOb": "caféer", "pluralBe": "caféerna", "group": "3", "translation": "café" },
    { "article": "ett", "singularOb": "erbjudande", "singularBe": "erbjudandet", "pluralOb": "erbjudanden", "pluralBe": "erbjudandena", "group": "4", "translation": "offer" },
    { "article": "ett", "singularOb": "fika", "singularBe": "fikat", "pluralOb": "-", "pluralBe": "-", "group": "4", "translation": "coffee break" },
    { "article": "ett", "singularOb": "garage", "singularBe": "garaget", "pluralOb": "garage", "pluralBe": "garagen", "group": "5", "translation": "garage" },
    { "article": "ett", "singularOb": "grönområde", "singularBe": "grönområdet", "pluralOb": "grönområden", "pluralBe": "grönområdena", "group": "4", "translation": "green area" },
    { "article": "ett", "singularOb": "gym", "singularBe": "gymmet", "pluralOb": "gym", "pluralBe": "gymmen", "group": "5", "translation": "gym" },
    { "article": "ett", "singularOb": "hälsningsfras", "singularBe": "hälsningsfrasen", "pluralOb": "hälsningsfraser", "pluralBe": "hälsningsfraserna", "group": "3", "translation": "greeting" },
    { "article": "ett", "singularOb": "hörn", "singularBe": "hörnet", "pluralOb": "hörn", "pluralBe": "hörnen", "group": "5", "translation": "corner" },
    { "article": "ett", "singularOb": "intresse", "singularBe": "intresset", "pluralOb": "intressen", "pluralBe": "intressena", "group": "4", "translation": "interest" },
    { "article": "ett", "singularOb": "kafé", "singularBe": "kaféet", "pluralOb": "kaféer", "pluralBe": "kaféerna", "group": "3", "translation": "café" },
    { "article": "ett", "singularOb": "konditori", "singularBe": "konditoriet", "pluralOb": "konditorier", "pluralBe": "konditorierna", "group": "3", "translation": "patisserie" },
    { "article": "ett", "singularOb": "meddelande", "singularBe": "meddelandet", "pluralOb": "meddelanden", "pluralBe": "meddelandena", "group": "4", "translation": "message" },
    { "article": "ett", "singularOb": "möte", "singularBe": "mötet", "pluralOb": "möten", "pluralBe": "mötena", "group": "4", "translation": "meeting" },
    { "article": "ett", "singularOb": "smycke", "singularBe": "smycket", "pluralOb": "smycken", "pluralBe": "smyckena", "group": "4", "translation": "jewelry" },

    // Group 5: - (ett words ending in consonant)
    { "article": "ett", "singularOb": "abonnemang", "singularBe": "abonnemanget", "pluralOb": "abonnemang", "pluralBe": "abonnemangen", "group": "5", "translation": "subscription" },
    { "article": "ett", "singularOb": "ägg", "singularBe": "ägget", "pluralOb": "ägg", "pluralBe": "äggen", "group": "5", "translation": "egg" },
    { "article": "ett", "singularOb": "alarm", "singularBe": "alarmet", "pluralOb": "alarm", "pluralBe": "alarmen", "group": "5", "translation": "alarm" },
    { "article": "ett", "singularOb": "alternativ", "singularBe": "alternativet", "pluralOb": "alternativ", "pluralBe": "alternativen", "group": "5", "translation": "alternative" },
    { "article": "ett", "singularOb": "ämne", "singularBe": "ämnet", "pluralOb": "ämnen", "pluralBe": "ämnena", "group": "4", "translation": "subject/topic" },
    { "article": "ett", "singularOb": "antal", "singularBe": "antalet", "pluralOb": "-", "pluralBe": "-", "group": "5", "translation": "number/amount" },
    { "article": "ett", "singularOb": "år", "singularBe": "året", "pluralOb": "år", "pluralBe": "åren", "group": "5", "translation": "year" },
    { "article": "ett", "singularOb": "avtal", "singularBe": "avtalet", "pluralOb": "avtal", "pluralBe": "avtalen", "group": "5", "translation": "agreement" },
    { "article": "ett", "singularOb": "badrum", "singularBe": "badrummet", "pluralOb": "badrum", "pluralBe": "badrummen", "group": "5", "translation": "bathroom" },
    { "article": "ett", "singularOb": "bär", "singularBe": "bäret", "pluralOb": "bär", "pluralBe": "bären", "group": "5", "translation": "berry" },
    { "article": "ett", "singularOb": "barn", "singularBe": "barnet", "pluralOb": "barn", "pluralBe": "barnen", "group": "5", "translation": "child" },
    { "article": "ett", "singularOb": "barnkalas", "singularBe": "barnkalaset", "pluralOb": "barnkalas", "pluralBe": "barnkalasen", "group": "5", "translation": "children's party" },
    { "article": "ett", "singularOb": "belopp", "singularBe": "beloppet", "pluralOb": "belopp", "pluralBe": "beloppen", "group": "5", "translation": "amount" },
    { "article": "ett", "singularOb": "berg", "singularBe": "berget", "pluralOb": "berg", "pluralBe": "bergen", "group": "5", "translation": "mountain" },
    { "article": "ett", "singularOb": "bestick", "singularBe": "besticket", "pluralOb": "bestick", "pluralBe": "besticken", "group": "5", "translation": "cutlery" },
    { "article": "ett", "singularOb": "bibliotek", "singularBe": "biblioteket", "pluralOb": "bibliotek", "pluralBe": "biblioteken", "group": "5", "translation": "library" },
    { "article": "ett", "singularOb": "bidrag", "singularBe": "bidraget", "pluralOb": "bidrag", "pluralBe": "bidragen", "group": "5", "translation": "contribution" },
    { "article": "ett", "singularOb": "bord", "singularBe": "bordet", "pluralOb": "bord", "pluralBe": "borden", "group": "5", "translation": "table" },
    { "article": "ett", "singularOb": "brev", "singularBe": "brevet", "pluralOb": "brev", "pluralBe": "breven", "group": "5", "translation": "letter" },
    { "article": "ett", "singularOb": "bröd", "singularBe": "brödet", "pluralOb": "bröd", "pluralBe": "bröden", "group": "5", "translation": "bread" },
    { "article": "ett", "singularOb": "bröllop", "singularBe": "bröllopet", "pluralOb": "bröllop", "pluralBe": "bröllopen", "group": "5", "translation": "wedding" },
    { "article": "ett", "singularOb": "dygn", "singularBe": "dygnet", "pluralOb": "dygn", "pluralBe": "dygnen", "group": "5", "translation": "24 hours" },
    { "article": "ett", "singularOb": "evenemang", "singularBe": "evenemanget", "pluralOb": "evenemang", "pluralBe": "evenemangen", "group": "5", "translation": "event" },
    { "article": "ett", "singularOb": "fält", "singularBe": "fältet", "pluralOb": "fält", "pluralBe": "fälten", "group": "5", "translation": "field" },
    { "article": "ett", "singularOb": "fönster", "singularBe": "fönstret", "pluralOb": "fönster", "pluralBe": "fönstren", "group": "5", "translation": "window" },
    { "article": "ett", "singularOb": "förhör", "singularBe": "förhöret", "pluralOb": "förhör", "pluralBe": "förhören", "group": "5", "translation": "interrogation/test" },
    { "article": "ett", "singularOb": "förråd", "singularBe": "förrådet", "pluralOb": "förråd", "pluralBe": "förråden", "group": "5", "translation": "storage room" },
    { "article": "ett", "singularOb": "förslag", "singularBe": "förslaget", "pluralOb": "förslag", "pluralBe": "förslagen", "group": "5", "translation": "suggestion" },
    { "article": "ett", "singularOb": "glas", "singularBe": "glaset", "pluralOb": "glas", "pluralBe": "glasen", "group": "5", "translation": "glass" },
    { "article": "ett", "singularOb": "golv", "singularBe": "golvet", "pluralOb": "golv", "pluralBe": "golven", "group": "5", "translation": "floor" },
    { "article": "ett", "singularOb": "halsband", "singularBe": "halsbandet", "pluralOb": "halsband", "pluralBe": "halsbanden", "group": "5", "translation": "necklace" },
    { "article": "ett", "singularOb": "hav", "singularBe": "havet", "pluralOb": "hav", "pluralBe": "haven", "group": "5", "translation": "sea" },
    { "article": "ett", "singularOb": "hem", "singularBe": "hemmet", "pluralOb": "hem", "pluralBe": "hemmen", "group": "5", "translation": "home" },
    { "article": "ett", "singularOb": "hemland", "singularBe": "hemlandet", "pluralOb": "hemländer", "pluralBe": "hemländerna", "group": "3 (irr)", "translation": "homeland" },
    { "article": "ett", "singularOb": "höghus", "singularBe": "höghuset", "pluralOb": "höghus", "pluralBe": "höghusen", "group": "5", "translation": "high-rise building" },
    { "article": "ett", "singularOb": "hotell", "singularBe": "hotellet", "pluralOb": "hotell", "pluralBe": "hotellen", "group": "5", "translation": "hotel" },
    { "article": "ett", "singularOb": "hus", "singularBe": "huset", "pluralOb": "hus", "pluralBe": "husen", "group": "5", "translation": "house" },
    { "article": "ett", "singularOb": "kö", "singularBe": "kön", "pluralOb": "köer", "pluralBe": "köerna", "group": "3", "translation": "queue" },
    { "article": "ett", "singularOb": "kök", "singularBe": "köket", "pluralOb": "kök", "pluralBe": "köken", "group": "5", "translation": "kitchen" },
    { "article": "ett", "singularOb": "kontrakt", "singularBe": "kontraktet", "pluralOb": "kontrakt", "pluralBe": "kontrakten", "group": "5", "translation": "contract" },
    { "article": "ett", "singularOb": "kylskåp", "singularBe": "kylskåpet", "pluralOb": "kylskåp", "pluralBe": "kylskåpen", "group": "5", "translation": "refrigerator" },
    { "article": "ett", "singularOb": "lakan", "singularBe": "lakanet", "pluralOb": "lakan", "pluralBe": "lakanen", "group": "5", "translation": "sheet (bed)" },
    { "article": "ett", "singularOb": "lån", "singularBe": "lånet", "pluralOb": "lån", "pluralBe": "lånen", "group": "5", "translation": "loan" },
    { "article": "ett", "singularOb": "land", "singularBe": "landet", "pluralOb": "länder", "pluralBe": "länderna", "group": "3 (irr)", "translation": "country" },
    { "article": "ett", "singularOb": "märke", "singularBe": "märket", "pluralOb": "märken", "pluralBe": "märkena", "group": "4", "translation": "brand/mark" },
    { "article": "ett", "singularOb": "nummer", "singularBe": "numret", "pluralOb": "nummer", "pluralBe": "numren", "group": "5", "translation": "number" },
    { "article": "ett", "singularOb": "paket", "singularBe": "paketet", "pluralOb": "paket", "pluralBe": "paketen", "group": "5", "translation": "package" },
    { "article": "ett", "singularOb": "päron", "singularBe": "päronet", "pluralOb": "päron", "pluralBe": "päronen", "group": "5", "translation": "pear" },
    { "article": "ett", "singularOb": "pris", "singularBe": "priset", "pluralOb": "priser", "pluralBe": "priserna", "group": "3", "translation": "price/prize" },
    { "article": "ett", "singularOb": "prov", "singularBe": "provet", "pluralOb": "prov", "pluralBe": "proven", "group": "5", "translation": "test" },
    { "article": "ett", "singularOb": "råd", "singularBe": "rådet", "pluralOb": "råd", "pluralBe": "råden", "group": "5", "translation": "advice" },
    { "article": "ett", "singularOb": "resultat", "singularBe": "resultatet", "pluralOb": "resultat", "pluralBe": "resultaten", "group": "5", "translation": "result" },
    { "article": "ett", "singularOb": "rum", "singularBe": "rummet", "pluralOb": "rum", "pluralBe": "rummen", "group": "5", "translation": "room" },
    { "article": "ett", "singularOb": "sovrum", "singularBe": "sovrummet", "pluralOb": "sovrum", "pluralBe": "sovrummen", "group": "5", "translation": "bedroom" },
    { "article": "ett", "singularOb": "språk", "singularBe": "språket", "pluralOb": "språk", "pluralBe": "språken", "group": "5", "translation": "language" },
    { "article": "ett", "singularOb": "stycke", "singularBe": "stycket", "pluralOb": "stycken", "pluralBe": "styckena", "group": "4", "translation": "piece" },
    { "article": "ett", "singularOb": "täcke", "singularBe": "täcket", "pluralOb": "täcken", "pluralBe": "täckena", "group": "4", "translation": "duvet" },
    { "article": "ett", "singularOb": "tåg", "singularBe": "tåget", "pluralOb": "tåg", "pluralBe": "tågen", "group": "5", "translation": "train" },
    { "article": "ett", "singularOb": "tält", "singularBe": "tältet", "pluralOb": "tält", "pluralBe": "tälten", "group": "5", "translation": "tent" },
    { "article": "ett", "singularOb": "uttryck", "singularBe": "uttrycket", "pluralOb": "uttryck", "pluralBe": "uttrycken", "group": "5", "translation": "expression" },
    { "article": "ett", "singularOb": "vardagsrum", "singularBe": "vardagsrummet", "pluralOb": "vardagsrum", "pluralBe": "vardagsrummen", "group": "5", "translation": "living room" },
    { "article": "ett", "singularOb": "vin", "singularBe": "vinet", "pluralOb": "viner", "pluralBe": "vinerna", "group": "3", "translation": "wine" },

    // Special / Others / Uncountables
    { "article": "en", "singularOb": "affär", "singularBe": "affären", "pluralOb": "affärer", "pluralBe": "affärerna", "group": "3", "translation": "store/business" },
    { "article": "en", "singularOb": "aktivitet", "singularBe": "aktiviteten", "pluralOb": "aktiviteter", "pluralBe": "aktiviteterna", "group": "3", "translation": "activity" },
    { "article": "en", "singularOb": "älskling", "singularBe": "älsklingen", "pluralOb": "älsklingar", "pluralBe": "älsklingarna", "group": "2", "translation": "darling" },
    { "article": "en", "singularOb": "ankomst", "singularBe": "ankomsten", "pluralOb": "ankomster", "pluralBe": "ankomsterna", "group": "3", "translation": "arrival" },
    { "article": "ett", "singularOb": "ansvar", "singularBe": "ansvaret", "pluralOb": "-", "pluralBe": "-", "group": "5", "translation": "responsibility" },
    { "article": "en", "singularOb": "älgstek", "singularBe": "älgsteken", "pluralOb": "älgstekar", "pluralBe": "älgstekarna", "group": "2", "translation": "moose roast" },
    { "article": "en", "singularOb": "bar", "singularBe": "baren", "pluralOb": "barer", "pluralBe": "barerna", "group": "3", "translation": "bar" },
    { "article": "en", "singularOb": "båt", "singularBe": "båten", "pluralOb": "båtar", "pluralBe": "båtarna", "group": "2", "translation": "boat" },
    { "article": "ett", "singularOb": "blåbär", "singularBe": "blåbäret", "pluralOb": "blåbär", "pluralBe": "blåbären", "group": "5", "translation": "blueberry" },
    { "article": "en", "singularOb": "blixt", "singularBe": "blixten", "pluralOb": "blixtar", "pluralBe": "blixtarna", "group": "2", "translation": "lightning bolt" },
    { "article": "en", "singularOb": "blomkål", "singularBe": "blomkålen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "cauliflower" },
    { "article": "en", "singularOb": "bokhandel", "singularBe": "bokhandeln", "pluralOb": "bokhandlar", "pluralBe": "bokhandlarna", "group": "2", "translation": "bookstore" },
    { "article": "en", "singularOb": "bostadsrätt", "singularBe": "bostadsrätten", "pluralOb": "bostadsrätter", "pluralBe": "bostadsrätterna", "group": "3", "translation": "condominium" },
    { "article": "en", "singularOb": "bottenvåning", "singularBe": "bottenvåningen", "pluralOb": "bottenvåningar", "pluralBe": "bottenvåningarna", "group": "2", "translation": "ground floor" },
    { "article": "en", "singularOb": "broccoli", "singularBe": "broccolin", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "broccoli" },
    { "article": "ett", "singularOb": "budget", "singularBe": "budgeten", "pluralOb": "budgetar", "pluralBe": "budgetarna", "group": "2", "translation": "budget" },
    { "article": "ett", "singularOb": "bus", "singularBe": "buset", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "mischief" },
    { "article": "ett", "singularOb": "centrum", "singularBe": "centrumet", "pluralOb": "centrum", "pluralBe": "centrumen", "group": "5", "translation": "center" },
    { "article": "ett", "singularOb": "choklad", "singularBe": "chokladen", "pluralOb": "choklader", "pluralBe": "chokladerna", "group": "3", "translation": "chocolate" },
    { "article": "ett", "singularOb": "cirkeldiagram", "singularBe": "cirkeldiagrammet", "pluralOb": "cirkeldiagram", "pluralBe": "cirkeldiagrammen", "group": "5", "translation": "pie chart" },
    { "article": "en", "singularOb": "dammvippa", "singularBe": "dammvippan", "pluralOb": "dammvippor", "pluralBe": "dammvipporna", "group": "1", "translation": "feather duster" },
    { "article": "en", "singularOb": "dåtid", "singularBe": "dåtiden", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "the past" },
    { "article": "ett", "singularOb": "distansuppgift", "singularBe": "distansuppgiften", "pluralOb": "distansuppgifter", "pluralBe": "distansuppgifterna", "group": "3", "translation": "distance assignment" },
    { "article": "ett", "singularOb": "djur", "singularBe": "djuret", "pluralOb": "djur", "pluralBe": "djuren", "group": "5", "translation": "animal" },
    { "article": "ett", "singularOb": "driftkostnad", "singularBe": "driftkostnaden", "pluralOb": "driftkostnader", "pluralBe": "driftkostnaderna", "group": "3", "translation": "operating cost" },
    { "article": "ett", "singularOb": "duntäcke", "singularBe": "duntäcket", "pluralOb": "duntäcken", "pluralBe": "duntäckena", "group": "4", "translation": "down duvet" },
    { "article": "en", "singularOb": "elkontakt", "singularBe": "elkontakten", "pluralOb": "elkontakter", "pluralBe": "elkontakterna", "group": "3", "translation": "electrical plug" },
    { "article": "ett", "singularOb": "eluttag", "singularBe": "eluttaget", "pluralOb": "eluttag", "pluralBe": "eluttagen", "group": "5", "translation": "electrical outlet" },
    { "article": "ett", "singularOb": "entréplan", "singularBe": "entréplanet", "pluralOb": "entréplan", "pluralBe": "entréplanen", "group": "5", "translation": "entrance floor" },
    { "article": "en", "singularOb": "ersättning", "singularBe": "ersättningen", "pluralOb": "ersättningar", "pluralBe": "ersättningarna", "group": "2", "translation": "compensation/replacement" },
    { "article": "en", "singularOb": "favoritfik", "singularBe": "favoritfiket", "pluralOb": "favoritfik", "pluralBe": "favoritfiken", "group": "5", "translation": "favorite cafe" },
    { "article": "en", "singularOb": "flicka", "singularBe": "flickan", "pluralOb": "flickor", "pluralBe": "flickorna", "group": "1", "translation": "girl" },
    { "article": "en", "singularOb": "fritid", "singularBe": "fritiden", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "free time" },
    { "article": "en", "singularOb": "gångavstånd", "singularBe": "gångavståndet", "pluralOb": "gångavstånd", "pluralBe": "gångavstånden", "group": "5", "translation": "walking distance" },
    { "article": "en", "singularOb": "glögg", "singularBe": "glöggen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "mulled wine" },
    { "article": "en", "singularOb": "kassa", "singularBe": "kassan", "pluralOb": "kassor", "pluralBe": "kassorna", "group": "1", "translation": "checkout" },
    { "article": "en", "singularOb": "kläder", "singularBe": "-", "pluralOb": "kläder", "pluralBe": "kläderna", "group": "3", "translation": "clothes" },
    { "article": "ett", "singularOb": "klädesplagg", "singularBe": "klädesplagget", "pluralOb": "klädesplagg", "pluralBe": "klädesplaggen", "group": "5", "translation": "garment" },
    { "article": "ett", "singularOb": "klagomål", "singularBe": "klagomålet", "pluralOb": "klagomål", "pluralBe": "klagomålen", "group": "5", "translation": "complaint" },
    { "article": "ett", "singularOb": "knytkalas", "singularBe": "knytkalaset", "pluralOb": "knytkalas", "pluralBe": "knytkalasen", "group": "5", "translation": "potluck" },
    { "article": "en", "singularOb": "koppling", "singularBe": "kopplingen", "pluralOb": "kopplingar", "pluralBe": "kopplingarna", "group": "2", "translation": "coupling/connection" },
    { "article": "en", "singularOb": "kostymbyxa", "singularBe": "kostymbyxan", "pluralOb": "kostymbyxor", "pluralBe": "kostymbyxorerna", "group": "1", "translation": "dress pants" },
    { "article": "ett", "singularOb": "läge", "singularBe": "läget", "pluralOb": "lägen", "pluralBe": "lägena", "group": "4", "translation": "location/situation" },
    { "article": "en", "singularOb": "lekplats", "singularBe": "lekplatsen", "pluralOb": "lekplatser", "pluralBe": "lekplatserna", "group": "3", "translation": "playground" },
    { "article": "en", "singularOb": "lön", "singularBe": "lönen", "pluralOb": "löner", "pluralBe": "lönerna", "group": "3", "translation": "salary" },
    { "article": "en", "singularOb": " Lucia", "singularBe": "Lucian", "pluralOb": "-", "pluralBe": "-", "group": "1", "translation": "Lucia" },
    { "article": "ett", "singularOb": "ludd", "singularBe": "luddet", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "lint/fuzz" },
    { "article": "ett", "singularOb": "mejl", "singularBe": "mejlet", "pluralOb": "mejl", "pluralBe": "mejlen", "group": "5", "translation": "email" },
    { "article": "en", "singularOb": "mening", "singularBe": "meningen", "pluralOb": "meningar", "pluralBe": "meningarna", "group": "2", "translation": "sentence/meaning" },
    { "article": "ett", "singularOb": "moln", "singularBe": "molnet", "pluralOb": "moln", "pluralBe": "molnen", "group": "5", "translation": "cloud" },
    { "article": "ett", "singularOb": "mörker", "singularBe": "mörkret", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "darkness" },
    { "article": "ett", "singularOb": "museum", "singularBe": "museet", "pluralOb": "museer", "pluralBe": "museerna", "group": "3", "translation": "museum" },
    { "article": "ett", "singularOb": "mynt", "singularBe": "myntet", "pluralOb": "mynt", "pluralBe": "mynten", "group": "5", "translation": "coin" },
    { "article": "en", "singularOb": "nyhet", "singularBe": "nyheten", "pluralOb": "nyheter", "pluralBe": "nyheterna", "group": "3", "translation": "news" },
    { "article": "en", "singularOb": "öppen spis", "singularBe": "öppna spisen", "pluralOb": "öppna spisar", "pluralBe": "öppna spisarna", "group": "2", "translation": "fireplace" },
    { "article": "ett", "singularOb": "örngott", "singularBe": "örngottet", "pluralOb": "örngott", "pluralBe": "örngotten", "group": "5", "translation": "pillowcase" },
    { "article": "ett", "singularOb": "pendeltåg", "singularBe": "pendeltåget", "pluralOb": "pendeltåg", "pluralBe": "pendeltågen", "group": "5", "translation": "commuter train" },
    { "article": "ett", "singularOb": "pendlingsavstånd", "singularBe": "pendlingsavståndet", "pluralOb": "pendlingsavstånd", "pluralBe": "pendlingsavstånden", "group": "5", "translation": "commuting distance" },
    { "article": "en", "singularOb": "personal", "singularBe": "personalen", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "staff" },
    { "article": "en", "singularOb": "presentkort", "singularBe": "presentkortet", "pluralOb": "presentkort", "pluralBe": "presentkorten", "group": "5", "translation": "gift card" },
    { "article": "en", "singularOb": "procent", "singularBe": "procenten", "pluralOb": "procent", "pluralBe": "procenten", "group": "5", "translation": "percent" },
    { "article": "ett", "singularOb": "skurhink", "singularBe": "skurhinken", "pluralOb": "skurhinkar", "pluralBe": "skurhinkarna", "group": "2", "translation": "mop bucket" },
    { "article": "en", "singularOb": "slangord", "singularBe": "slangordet", "pluralOb": "slangord", "pluralBe": "slangorden", "group": "5", "translation": "slang word" },
    { "article": "en", "singularOb": "småstad", "singularBe": "småstaden", "pluralOb": "småstäder", "pluralBe": "småstäderna", "group": "3 (irr)", "translation": "small town" },
    { "article": "ett", "singularOb": "smör", "singularBe": "smöret", "pluralOb": "-", "pluralBe": "-", "group": "uncount", "translation": "butter" },
    { "article": "ett", "singularOb": "sms", "singularBe": "sms:et", "pluralOb": "sms", "pluralBe": "sms:en", "group": "5", "translation": "SMS" },
    { "article": "en", "singularOb": "sms-tråd", "singularBe": "sms-tråden", "pluralOb": "sms-trådar", "pluralBe": "sms-trådarna", "group": "2", "translation": "SMS thread" },
    { "article": "en", "singularOb": "spårbyte", "singularBe": "spårbytet", "pluralOb": "spårbyten", "pluralBe": "spårbytena", "group": "4", "translation": "track change" },
    { "article": "ett", "singularOb": "stapeldiagram", "singularBe": "stapeldiagrammet", "pluralOb": "stapeldiagram", "pluralBe": "stapeldiagrammen", "group": "5", "translation": "bar chart" },
    { "article": "en", "singularOb": "strumpa", "singularBe": "strumpan", "pluralOb": "strumpor", "pluralBe": "strumporna", "group": "1", "translation": "sock" },
    { "article": "ett", "singularOb": "telefonskal", "singularBe": "telefonskalet", "pluralOb": "telefonskal", "pluralBe": "telefonskalen", "group": "5", "translation": "phone case" },
    { "article": "en", "singularOb": "tevebänk", "singularBe": "tevebänken", "pluralOb": "tevebänkar", "pluralBe": "tevebänkarna", "group": "2", "translation": "TV stand" },
    { "article": "en", "singularOb": "torktumlare", "singularBe": "torktumlaren", "pluralOb": "torktumlare", "pluralBe": "torktumlarna", "group": "5", "translation": "dryer" },
    { "article": "en", "singularOb": "tunnelbana", "singularBe": "tunnelbanan", "pluralOb": "tunnelbanor", "pluralBe": "tunnelbanorna", "group": "1", "translation": "metro" },
    { "article": "en", "singularOb": "tvättstuga", "singularBe": "tvättstugan", "pluralOb": "tvättstugor", "pluralBe": "tvättstugorna", "group": "1", "translation": "laundry room" },
    { "article": "en", "singularOb": "vardag", "singularBe": "vardagen", "pluralOb": "vardagar", "pluralBe": "vardagarna", "group": "2", "translation": "weekday" }
];