// file:///Users/bentoblitzz/Documents/Playground/svenska_ovning/content/en/grammatik/verb/verbkonjugation/verb_A1A2/verbkonjugation_A1A2_data.js

// here's the table header: | Imperativ [input] | Infinitiv [hint] | Presens [input] | Preteritum [input] Supinum [input] | Group [group] | Translation [translation] |



const verbA1A2_Data = [
  { "imperativ": "äg", "infinitiv": "äga", "presens": "äger", "preteritum": "ägde", "supinum": "ägt", "group":"2a", "translation": "to own" },
  { "imperativ": "åk", "infinitiv": "åka", "presens": "åker", "preteritum": "åkte", "supinum": "åkt", "group":"4", "translation": "to go/travel" },
  { "imperativ": "ändra", "infinitiv": "ändra", "presens": "ändrar", "preteritum": "ändrade", "supinum": "ändrat", "group":"1", "translation": "to change" },
  { "imperativ": "ångra", "infinitiv": "ångra", "presens": "ångrar", "preteritum": "ångrade", "supinum": "ångrat", "group":"1", "translation": "to regret" },
  { "imperativ": "använd", "infinitiv": "använda", "presens": "använder", "preteritum": "använde", "supinum": "använt", "group":"2a", "translation": "to use" },
  { "imperativ": "arbeta", "infinitiv": "arbeta", "presens": "arbetar", "preteritum": "arbetade", "supinum": "arbetat", "group":"1", "translation": "to work" },
  { "imperativ": "åska", "infinitiv": "åska", "presens": "åskar", "preteritum": "åskade", "supinum": "åskat", "group":"1", "translation": "to thunder" },
  { "imperativ": "ät", "infinitiv": "äta", "presens": "äter", "preteritum": "åt", "supinum": "ätit", "group":"4a it-verb", "translation": "to eat" },
  { "imperativ": "avsluta", "infinitiv": "avsluta", "presens": "avslutar", "preteritum": "avslutade", "supinum": "avslutat", "group":"1", "translation": "to finish/end" },
  { "imperativ": "bada", "infinitiv": "bada", "presens": "badar", "preteritum": "badade", "supinum": "badat", "group":"1", "translation": "to bathe/swim" },
  { "imperativ": "baka", "infinitiv": "baka", "presens": "bakar", "preteritum": "bakade", "supinum": "bakat", "group":"1", "translation": "to bake" },
  { "imperativ": "basta", "infinitiv": "basta", "presens": "bastar", "preteritum": "bastade", "supinum": "bastat", "group":"1", "translation": "to have a sauna" },
  { "imperativ": "bearbeta", "infinitiv": "bearbeta", "presens": "bearbetar", "preteritum": "bearbetade", "supinum": "bearbetat", "group":"1", "translation": "to process/work on" },
  { "imperativ": "-", "infinitiv": "behöva", "presens": "behöver", "preteritum": "behövde", "supinum": "behövt", "group":"2a", "translation": "to need" },
  { "imperativ": "berätta", "infinitiv": "berätta", "presens": "berättar", "preteritum": "berättade", "supinum": "berättat", "group":"1", "translation": "to tell/narrate" },
  { "imperativ": "-", "infinitiv": "bero (på)", "presens": "beror", "preteritum": "berodde", "supinum": "berott", "group":"3", "translation": "to depend (on)" },
  { "imperativ": "beskriv", "infinitiv": "beskriva", "presens": "beskriver", "preteritum": "beskrev", "supinum": "beskrivit", "group":"4a it-verb", "translation": "to describe" },
  { "imperativ": "besök", "infinitiv": "besöka", "presens": "besöker", "preteritum": "besökte", "supinum": "besökt", "group":"2b", "translation": "to visit" },
  { "imperativ": "beställ", "infinitiv": "beställa", "presens": "beställer", "preteritum": "beställde", "supinum": "beställt", "group":"2a", "translation": "to order" },
  { "imperativ": "bestäm", "infinitiv": "bestämma", "presens": "bestämmer", "preteritum": "bestämde", "supinum": "bestämt", "group":"2a", "translation": "to order" },

  { "imperativ": "betala", "infinitiv": "betala", "presens": "betalar", "preteritum": "betalade", "supinum": "betalat", "group":"1", "translation": "to pay" },
  { "imperativ": "bjud", "infinitiv": "bjuda", "presens": "bjuder", "preteritum": "bjöd", "supinum": "bjudit", "group":"4a it-verb", "translation": "to invite/offer" },
  { "imperativ": "blås", "infinitiv": "blåsa", "presens": "blåser", "preteritum": "blåste", "supinum": "blåst", "group":"2", "translation": "to blow" },
  { "imperativ": "bli", "infinitiv": "bli", "presens": "blir", "preteritum": "blev", "supinum": "blivit", "group":"4a it-verb", "translation": "to become" },
  { "imperativ": "blixtra", "infinitiv": "blixtra", "presens": "blixtrar", "preteritum": "blixtrade", "supinum": "blixtrat", "group":"1", "translation": "to flash (lightning)" },
  { "imperativ": "bo", "infinitiv": "bo", "presens": "bor", "preteritum": "bodde", "supinum": "bott", "group":"3", "translation": "to live/reside" },
  { "imperativ": "böj", "infinitiv": "böja", "presens": "böjer", "preteritum": "böjde", "supinum": "böjt", "group":"2", "translation": "to bend/conjugate" },
  { "imperativ": "boka", "infinitiv": "boka", "presens": "bokar", "preteritum": "bokade", "supinum": "bokat", "group":"1", "translation": "to book" },
  { "imperativ": "-", "infinitiv": "böra", "presens": "bör", "preteritum": "borde", "supinum": "bort", "group":"4 (modal)", "translation": "should/ought to" },
  { "imperativ": "börja", "infinitiv": "börja", "presens": "börjar", "preteritum": "började", "supinum": "börjat", "group":"1", "translation": "to start" },
  { "imperativ": "borra", "infinitiv": "borra", "presens": "borrar", "preteritum": "borrade", "supinum": "borrat", "group":"1", "translation": "to drill" },
  { "imperativ": "borsta", "infinitiv": "borsta", "presens": "borstar", "preteritum": "borstade", "supinum": "borstat", "group":"1", "translation": "to brush" },
  { "imperativ": "bråka", "infinitiv": "bråka", "presens": "bråkar", "preteritum": "bråkade", "supinum": "bråkat", "group":"1", "translation": "to fight/make trouble" },
  { "imperativ": "bruka", "infinitiv": "bruka", "presens": "brukar", "preteritum": "brukade", "supinum": "brukat", "group":"1", "translation": "to usually do" },
  { "imperativ": "byt", "infinitiv": "byta", "presens": "byter", "preteritum": "bytte", "supinum": "bytt", "group":"2", "translation": "to change/exchange" },
  { "imperativ": "chatta", "infinitiv": "chatta", "presens": "chattar", "preteritum": "chattade", "supinum": "chattat", "group":"1", "translation": "to chat" },
  { "imperativ": "cykla", "infinitiv": "cykla", "presens": "cyklar", "preteritum": "cyklade", "supinum": "cyklat", "group":"1", "translation": "to bicycle" },
  { "imperativ": "dammsug", "infinitiv": "dammsuga", "presens": "dammsuger", "preteritum": "dammsög", "supinum": "dammsugit", "group":"4a it-verb", "translation": "to vacuum" },
  { "imperativ": "dansa", "infinitiv": "dansa", "presens": "dansar", "preteritum": "dansade", "supinum": "dansat", "group":"1", "translation": "to dance" },
  { "imperativ": "dela", "infinitiv": "dela", "presens": "delar", "preteritum": "delade", "supinum": "delat", "group":"1", "translation": "to share/divide" },
  { "imperativ": "diska", "infinitiv": "diska", "presens": "diskar", "preteritum": "diskade", "supinum": "diskat", "group":"1", "translation": "to wash dishes" },
  { "imperativ": "diskutera", "infinitiv": "diskutera", "presens": "diskuterar", "preteritum": "diskuterade", "supinum": "diskuterat", "group":"1", "translation": "to discuss" },
  { "imperativ": "dölj", "infinitiv": "dölja", "presens": "döljer", "preteritum": "dolde", "supinum": "dolt", "group":"2", "translation": "to hide" },
  { "imperativ": "dra", "infinitiv": "dra", "presens": "drar", "preteritum": "drog", "supinum": "dragit", "group":"4a it-verb", "translation": "to pull" },
  { "imperativ": "drick", "infinitiv": "dricka", "presens": "dricker", "preteritum": "drack", "supinum": "drickit", "group":"4a it-verb", "translation": "to drink" },
  { "imperativ": "dröm", "infinitiv": "drömma", "presens": "drömmer", "preteritum": "drömde", "supinum": "drömt", "group":"2", "translation": "to dream" },
  { "imperativ": "duscha", "infinitiv": "duscha", "presens": "duschar", "preteritum": "duschade", "supinum": "duschat", "group":"1", "translation": "to shower" },
  { "imperativ": "elda", "infinitiv": "elda", "presens": "eldar", "preteritum": "eldade", "supinum": "eldat", "group":"1", "translation": "to burn/fire" },
  { "imperativ": "fastna", "infinitiv": "fastna", "presens": "fastnar", "preteritum": "fastnade", "supinum": "fastnat", "group":"1", "translation": "to get stuck" },
  { "imperativ": "fika", "infinitiv": "fika", "presens": "fikar", "preteritum": "fikade", "supinum": "fikat", "group":"1", "translation": "to have coffee" },
  { "imperativ": "finns", "infinitiv": "finnas", "presens": "finns", "preteritum": "fanns", "supinum": "funnits", "group":"4 (dep)", "translation": "to exist/be" },
  { "imperativ": "fira", "infinitiv": "fira", "presens": "firar", "preteritum": "firade", "supinum": "firat", "group":"1", "translation": "to celebrate" },
  { "imperativ": "fiska", "infinitiv": "fiska", "presens": "fiskar", "preteritum": "fiskade", "supinum": "fiskat", "group":"1", "translation": "to fish" },
  { "imperativ": "fixa", "infinitiv": "fixa", "presens": "fixar", "preteritum": "fixade", "supinum": "fixat", "group":"1", "translation": "to fix" },
  { "imperativ": "flyg", "infinitiv": "flyga", "presens": "flyger", "preteritum": "flög", "supinum": "flugit", "group":"4a it-verb", "translation": "to fly" },
  { "imperativ": "flytta", "infinitiv": "flytta", "presens": "flyttar", "preteritum": "flyttade", "supinum": "flyttat", "group":"1", "translation": "to move" },
  { "imperativ": "följ", "infinitiv": "följa", "presens": "följer", "preteritum": "följde", "supinum": "följt", "group":"2", "translation": "to follow" },
  { "imperativ": "förbered", "infinitiv": "förbereda", "presens": "förbereder", "preteritum": "förberedde", "supinum": "förberett", "group":"2", "translation": "to prepare" },
  { "imperativ": "föredra", "infinitiv": "föredra", "presens": "föredrar", "preteritum": "föredrog", "supinum": "föredragit", "group":"4a it-verb", "translation": "to prefer" },
  { "imperativ": "föreslå", "infinitiv": "föreslå", "presens": "föreslår", "preteritum": "föreslog", "supinum": "föreslagit", "group":"4a it-verb", "translation": "to suggest" },
  { "imperativ": "förklara", "infinitiv": "förklara", "presens": "förklarar", "preteritum": "förklarade", "supinum": "förklarat", "group":"1", "translation": "to explain" },
  { "imperativ": "förneka", "infinitiv": "förneka", "presens": "förnekar", "preteritum": "förnekade", "supinum": "förnekat", "group":"1", "translation": "to deny" },
  { "imperativ": "förstå", "infinitiv": "förstå", "presens": "förstår", "preteritum": "förstod", "supinum": "förstått", "group":"4", "translation": "to understand" },
  { "imperativ": "försvinn", "infinitiv": "försvinna", "presens": "försvinner", "preteritum": "försvann", "supinum": "försvunnit", "group":"4a it-verb", "translation": "to disappear" },
  { "imperativ": "fortsätt", "infinitiv": "fortsätta", "presens": "fortsätter", "preteritum": "fortsatte", "supinum": "fortsatt", "group":"4 (irr)", "translation": "to continue" },
  { "imperativ": "förvänta", "infinitiv": "förvänta", "presens": "förväntar", "preteritum": "förväntade", "supinum": "förväntat", "group":"1", "translation": "to expect" },
  { "imperativ": "frys", "infinitiv": "frysa", "presens": "fryser", "preteritum": "frös", "supinum": "frusit", "group":"4a it-verb", "translation": "to freeze" },
  { "imperativ": "fundera", "infinitiv": "fundera", "presens": "funderar", "preteritum": "funderade", "supinum": "funderat", "group":"1", "translation": "to ponder/think" },
  { "imperativ": "fynda", "infinitiv": "fynda", "presens": "fyndar", "preteritum": "fyndade", "supinum": "fyndat", "group":"1", "translation": "to find a bargain" },
  { "imperativ": "gå", "infinitiv": "gå", "presens": "går", "preteritum": "gick", "supinum": "gått", "group":"4", "translation": "to walk/go" },
  { "imperativ": "gift", "infinitiv": "gifta", "presens": "gifter", "preteritum": "gifte", "supinum": "gift", "group":"2", "translation": "to marry" },
  { "imperativ": "gissa", "infinitiv": "gissa", "presens": "gissar", "preteritum": "gissade", "supinum": "gissat", "group":"1", "translation": "to guess" },
  { "imperativ": "gör", "infinitiv": "göra", "presens": "gör", "preteritum": "gjorde", "supinum": "gjort", "group":"4 (irr)", "translation": "to do/make" },
  { "imperativ": "grilla", "infinitiv": "grilla", "presens": "grillar", "preteritum": "grillade", "supinum": "grillat", "group":"1", "translation": "to grill" },
  { "imperativ": "ha", "infinitiv": "ha", "presens": "har", "preteritum": "hade", "supinum": "haft", "group":"4 (irr)", "translation": "to have" },
  { "imperativ": "håll", "infinitiv": "hålla", "presens": "håller", "preteritum": "höll", "supinum": "hållit", "group":"4a it-verb", "translation": "to hold" },
  { "imperativ": "hälsa", "infinitiv": "hälsa", "presens": "hälsar", "preteritum": "hälsade", "supinum": "hälsat", "group":"1", "translation": "to greet" },
  { "imperativ": "hämta", "infinitiv": "hämta", "presens": "hämtar", "preteritum": "hämtade", "supinum": "hämtat", "group":"1", "translation": "to fetch" },
  { "imperativ": "händ", "infinitiv": "hända", "presens": "händer", "preteritum": "hände", "supinum": "hänt", "group":"2", "translation": "to happen" },
  { "imperativ": "handla", "infinitiv": "handla", "presens": "handlar", "preteritum": "handlade", "supinum": "handlat", "group":"1", "translation": "to shop/act" },
  { "imperativ": "häng", "infinitiv": "hänga", "presens": "hänger", "preteritum": "hängde", "supinum": "hängt", "group":"2", "translation": "to hang" },
  { "imperativ": "het", "infinitiv": "heta", "presens": "heter", "preteritum": "hette", "supinum": "hetat", "group":"2", "translation": "to be called" },
  { "imperativ": "hinn", "infinitiv": "hinna", "presens": "hinner", "preteritum": "hann", "supinum": "hunnit", "group":"4a it-verb", "translation": "to have time" },
  { "imperativ": "hjälp", "infinitiv": "hjälpa", "presens": "hjälper", "preteritum": "hjälpte", "supinum": "hjälpt", "group":"2", "translation": "to help" },
  { "imperativ": "hoppas", "infinitiv": "hoppas", "presens": "hoppas", "preteritum": "hoppades", "supinum": "hoppats", "group":"1 (dep)", "translation": "to hope" },
  { "imperativ": "hör", "infinitiv": "höra", "presens": "hör", "preteritum": "hörde", "supinum": "hört", "group":"2", "translation": "to hear" },
  { "imperativ": "hugg", "infinitiv": "hugga", "presens": "hugger", "preteritum": "högg", "supinum": "huggit", "group":"4a it-verb", "translation": "to chop" },
  { "imperativ": "hyr", "infinitiv": "hyra", "presens": "hyr", "preteritum": "hyrde", "supinum": "hyrt", "group":"2", "translation": "to rent" },
  { "imperativ": "informera", "infinitiv": "informera", "presens": "informerar", "preteritum": "informerade", "supinum": "informerat", "group":"1", "translation": "to inform" },
  { "imperativ": "inred", "infinitiv": "inreda", "presens": "inreder", "preteritum": "inredde", "supinum": "inrett", "group":"2", "translation": "to furnish" },
  { "imperativ": "jobba", "infinitiv": "jobba", "presens": "jobbar", "preteritum": "jobbade", "supinum": "jobbat", "group":"1", "translation": "to work" },
  { "imperativ": "jogga", "infinitiv": "jogga", "presens": "joggar", "preteritum": "joggade", "supinum": "joggat", "group":"1", "translation": "to jog" },
  { "imperativ": "känn", "infinitiv": "känna", "presens": "känner", "preteritum": "kände", "supinum": "känt", "group":"2", "translation": "to feel/know" },
  { "imperativ": "kasta", "infinitiv": "kasta", "presens": "kastar", "preteritum": "kastade", "supinum": "kastat", "group":"1", "translation": "to throw" },
  { "imperativ": "klaga", "infinitiv": "klaga", "presens": "klagar", "preteritum": "klagade", "supinum": "klagat", "group":"1", "translation": "to complain" },
  { "imperativ": "klättra", "infinitiv": "klättra", "presens": "klättrar", "preteritum": "klättrade", "supinum": "klättrat", "group":"1", "translation": "to climb" },
  { "imperativ": "koka", "infinitiv": "koka", "presens": "kokar", "preteritum": "kokade", "supinum": "kokat", "group":"1", "translation": "to boil" },
  { "imperativ": "kolla", "infinitiv": "kolla", "presens": "kollar", "preteritum": "kollade", "supinum": "kollat", "group":"1", "translation": "to check" },
  { "imperativ": "kom", "infinitiv": "komma", "presens": "kommer", "preteritum": "kom", "supinum": "kommit", "group":"4a it-verb", "translation": "to come" },
  { "imperativ": "komplettera", "infinitiv": "komplettera", "presens": "kompletterar", "preteritum": "kompletterade", "supinum": "kompletterat", "group":"1", "translation": "to complete" },
  { "imperativ": "koncentrera", "infinitiv": "koncentrera", "presens": "koncentrerar", "preteritum": "koncentrerade", "supinum": "koncentrerat", "group":"1", "translation": "to concentrate" },
  { "imperativ": "konsumera", "infinitiv": "konsumera", "presens": "konsumerar", "preteritum": "konsumerade", "supinum": "konsumerat", "group":"1", "translation": "to consume" },
  { "imperativ": "kontrollera", "infinitiv": "kontrollera", "presens": "kontrollerar", "preteritum": "kontrollerade", "supinum": "kontrollerat", "group":"1", "translation": "to check/control" },
  { "imperativ": "köp", "infinitiv": "köpa", "presens": "köper", "preteritum": "köpte", "supinum": "köpt", "group":"2", "translation": "to buy" },
  { "imperativ": "koppla av", "infinitiv": "koppla av", "presens": "kopplar av", "preteritum": "kopplade av", "supinum": "kopplat av", "group":"1", "translation": "to relax" },
  { "imperativ": "kör", "infinitiv": "köra", "presens": "kör", "preteritum": "körde", "supinum": "kört", "group":"2", "translation": "to drive" },
  { "imperativ": "-", "infinitiv": "kunna", "presens": "kan", "preteritum": "kunde", "supinum": "kunnat", "group":"4 (modal)", "translation": "can/be able to" },
  { "imperativ": "ladda", "infinitiv": "ladda", "presens": "laddar", "preteritum": "laddade", "supinum": "laddat", "group":"1", "translation": "to charge/load" },
  { "imperativ": "laga", "infinitiv": "laga", "presens": "lagar", "preteritum": "lagade", "supinum": "lagat", "group":"1", "translation": "to cook/fix" },
  { "imperativ": "lägg", "infinitiv": "lägga", "presens": "lägger", "preteritum": "la(de)", "supinum": "lagt", "group":"4", "translation": "to put/lay" },
  { "imperativ": "lämna", "infinitiv": "lämna", "presens": "lämnar", "preteritum": "lämnade", "supinum": "lämnat", "group":"1", "translation": "to leave" },
  { "imperativ": "låna", "infinitiv": "låna", "presens": "lånar", "preteritum": "lånade", "supinum": "lånat", "group":"1", "translation": "to borrow/lend" },
  { "imperativ": "läs", "infinitiv": "läsa", "presens": "läser", "preteritum": "läste", "supinum": "läst", "group":"2", "translation": "to read" },
  { "imperativ": "låt", "infinitiv": "låta", "presens": "låter", "preteritum": "lät", "supinum": "låtit", "group":"4a it-verb", "translation": "to let/sound" },
  { "imperativ": "låtsas", "infinitiv": "låtsas", "presens": "låtsas", "preteritum": "låtsades", "supinum": "låtsats", "group":"1 (dep)", "translation": "to pretend" },
  { "imperativ": "leasa", "infinitiv": "leasa", "presens": "leasar", "preteritum": "leasade", "supinum": "leasat", "group":"1", "translation": "to lease" },
  { "imperativ": "lek", "infinitiv": "leka", "presens": "leker", "preteritum": "lekte", "supinum": "lekt", "group":"2", "translation": "to play (kids)" },
  { "imperativ": "lev", "infinitiv": "leva", "presens": "lever", "preteritum": "levde", "supinum": "levt", "group":"2", "translation": "to live/be alive" },
  { "imperativ": "ligg", "infinitiv": "ligga", "presens": "ligger", "preteritum": "låg", "supinum": "legat", "group":"4", "translation": "to lie down" },
  { "imperativ": "ljug", "infinitiv": "ljuga", "presens": "ljuger", "preteritum": "ljög", "supinum": "ljugit", "group":"4a it-verb", "translation": "to lie" },
  { "imperativ": "logga in", "infinitiv": "logga in", "presens": "loggar in", "preteritum": "loggade in", "supinum": "loggat in", "group":"1", "translation": "to log in" },
  { "imperativ": "lyssna", "infinitiv": "lyssna", "presens": "lyssnar", "preteritum": "lyssnade", "supinum": "lyssnat", "group":"1", "translation": "to listen" },
  { "imperativ": "må", "infinitiv": "må", "presens": "mår", "preteritum": "mådde", "supinum": "mått", "group":"3", "translation": "to feel (well/sick)" },
  { "imperativ": "markera", "infinitiv": "markera", "presens": "markerar", "preteritum": "markerade", "supinum": "markerat", "group":"1", "translation": "to mark/highlight" },
  { "imperativ": "-", "infinitiv": "måste", "presens": "måste", "preteritum": "måste", "supinum": "måst", "group":"4 (modal)", "translation": "must" },
  { "imperativ": "messa", "infinitiv": "messa", "presens": "messar", "preteritum": "messade", "supinum": "messat", "group":"1", "translation": "to text" },
  { "imperativ": "minns", "infinitiv": "minnas", "presens": "minns", "preteritum": "mindes", "supinum": "mints", "group":"2 (dep)", "translation": "to remember" },
  { "imperativ": "moppa", "infinitiv": "moppa", "presens": "moppar", "preteritum": "moppade", "supinum": "moppat", "group":"1", "translation": "to mop" },
  { "imperativ": "njut", "infinitiv": "njuta", "presens": "njuter", "preteritum": "njöt", "supinum": "njutit", "group":"4a it-verb", "translation": "to enjoy" },
  { "imperativ": "nys", "infinitiv": "nysa", "presens": "nyser", "preteritum": "nyste", "supinum": "nyst", "group":"2", "translation": "to sneeze" },
  { "imperativ": "odla", "infinitiv": "odla", "presens": "odlar", "preteritum": "odlade", "supinum": "odlat", "group":"1", "translation": "to grow/cultivate" },
  { "imperativ": "organisera", "infinitiv": "organisera", "presens": "organiserar", "preteritum": "organiserade", "supinum": "organiserat", "group":"1", "translation": "to organize" },
  { "imperativ": "orka", "infinitiv": "orka", "presens": "orkar", "preteritum": "orkade", "supinum": "orkat", "group":"1", "translation": "to have the energy" },
  { "imperativ": "oroa", "infinitiv": "oroa", "presens": "oroar", "preteritum": "oroade", "supinum": "oroat", "group":"1", "translation": "to worry" },
  { "imperativ": "paddla", "infinitiv": "paddla", "presens": "paddlar", "preteritum": "paddlade", "supinum": "paddlat", "group":"1", "translation": "to paddle" },
  { "imperativ": "pendla", "infinitiv": "pendla", "presens": "pendlar", "preteritum": "pendlade", "supinum": "pendlat", "group":"1", "translation": "to commute" },
  { "imperativ": "planera", "infinitiv": "planera", "presens": "planerar", "preteritum": "planerade", "supinum": "planerat", "group":"1", "translation": "to plan" },
  { "imperativ": "plocka", "infinitiv": "plocka", "presens": "plockar", "preteritum": "plockade", "supinum": "plockat", "group":"1", "translation": "to pick" },
  { "imperativ": "prata", "infinitiv": "prata", "presens": "pratar", "preteritum": "pratade", "supinum": "pratat", "group":"1", "translation": "to talk" },
  { "imperativ": "prenumerera", "infinitiv": "prenumerera", "presens": "prenumererar", "preteritum": "prenumererade", "supinum": "prenumererat", "group":"1", "translation": "to subscribe" },
  { "imperativ": "promenera", "infinitiv": "promenera", "presens": "promenerar", "preteritum": "promenerar", "supinum": "promenerat", "group":"1", "translation": "to walk" },
  { "imperativ": "prova", "infinitiv": "prova", "presens": "provar", "preteritum": "provade", "supinum": "provat", "group":"1", "translation": "to try/test" },
  { "imperativ": "pruta", "infinitiv": "pruta", "presens": "prutar", "preteritum": "prutade", "supinum": "prutat", "group":"1", "translation": "to haggle" },
  { "imperativ": "putsa", "infinitiv": "putsa", "presens": "putsar", "preteritum": "putsade", "supinum": "putsat", "group":"1", "translation": "to polish" },
  { "imperativ": "räkna", "infinitiv": "räkna", "presens": "räknar", "preteritum": "räknade", "supinum": "räknat", "group":"1", "translation": "to count" },
  { "imperativ": "regna", "infinitiv": "regna", "presens": "regnar", "preteritum": "regnade", "supinum": "regnat", "group":"1", "translation": "to rain" },
  { "imperativ": "renovera", "infinitiv": "renovera", "presens": "renoverar", "preteritum": "renoverade", "supinum": "renoverat", "group":"1", "translation": "to renovate" },
  { "imperativ": "repetera", "infinitiv": "repetera", "presens": "repeterar", "preteritum": "repeterade", "supinum": "repeterat", "group":"1", "translation": "to repeat" },
  { "imperativ": "res", "infinitiv": "resa", "presens": "reser", "preteritum": "reste", "supinum": "rest", "group":"2", "translation": "to travel" },
  { "imperativ": "ring", "infinitiv": "ringa", "presens": "ringer", "preteritum": "ringde", "supinum": "ringt", "group":"2", "translation": "to call/ring" },
  { "imperativ": "rök", "infinitiv": "röka", "presens": "röker", "preteritum": "rökte", "supinum": "rökt", "group":"2", "translation": "to smoke" },
  { "imperativ": "säg", "infinitiv": "säga", "presens": "säger", "preteritum": "sa(de)", "supinum": "sagt", "group":"4 (irr)", "translation": "to say" },
  { "imperativ": "sakna", "infinitiv": "sakna", "presens": "saknar", "preteritum": "saknade", "supinum": "saknat", "group":"1", "translation": "to miss/lack" },
  { "imperativ": "sälj", "infinitiv": "sälja", "presens": "säljer", "preteritum": "sålde", "supinum": "sålt", "group":"2", "translation": "to sell" },
  { "imperativ": "sätt", "infinitiv": "sätta", "presens": "sätter", "preteritum": "satte", "supinum": "satt", "group":"4 (irr)", "translation": "to put/set" },
  { "imperativ": "shoppa", "infinitiv": "shoppa", "presens": "shoppar", "preteritum": "shoppade", "supinum": "shoppat", "group":"1", "translation": "to shop" },
  { "imperativ": "simma", "infinitiv": "simma", "presens": "simmar", "preteritum": "simmade", "supinum": "simmat", "group":"1", "translation": "to swim" },
  { "imperativ": "sitt", "infinitiv": "sitta", "presens": "sitter", "preteritum": "satt", "supinum": "suttit", "group":"4a it-verb", "translation": "to sit" },
  { "imperativ": "sjung", "infinitiv": "sjunga", "presens": "sjunger", "preteritum": "sjäng", "supinum": "sjungit", "group":"4a it-verb", "translation": "to sing" },
  { "imperativ": "skaffa", "infinitiv": "skaffa", "presens": "skaffar", "preteritum": "skaffade", "supinum": "skaffat", "group":"1", "translation": "to get/acquire" },
  { "imperativ": "skäll", "infinitiv": "skälla", "presens": "skäller", "preteritum": "skällde", "supinum": "skällt", "group":"2", "translation": "to bark" },
  { "imperativ": "skejta", "infinitiv": "skejta", "presens": "skejtar", "preteritum": "skejtade", "supinum": "skejtat", "group":"1", "translation": "to skate" },
  { "imperativ": "skicka", "infinitiv": "skicka", "presens": "skickar", "preteritum": "skickade", "supinum": "skickat", "group":"1", "translation": "to send" },
  { "imperativ": "skin", "infinitiv": "skina", "presens": "skiner", "preteritum": "sken", "supinum": "skinit", "group":"4a it-verb", "translation": "to shine" },
  { "imperativ": "skjut", "infinitiv": "skjuta", "presens": "skjuter", "preteritum": "sköt", "supinum": "skjutit", "group":"4a it-verb", "translation": "to shoot" },
  { "imperativ": "skoja", "infinitiv": "skoja", "presens": "skojar", "preteritum": "skojade", "supinum": "skojat", "group":"1", "translation": "to joke" },
  { "imperativ": "-", "infinitiv": "skola", "presens": "ska", "preteritum": "skulle", "supinum": "skolat", "group":"4 (modal)", "translation": "will/shall" },
  { "imperativ": "skratta", "infinitiv": "skratta", "presens": "skrattar", "preteritum": "skrattade", "supinum": "skrattat", "group":"1", "translation": "to laugh" },
  { "imperativ": "skriv", "infinitiv": "skriva", "presens": "skriver", "preteritum": "skrev", "supinum": "skrivit", "group":"4a it-verb", "translation": "to write" },
  { "imperativ": "skrubba", "infinitiv": "skrubba", "presens": "skrubbar", "preteritum": "skrubbade", "supinum": "skrubbat", "group":"1", "translation": "to scrub" },
  { "imperativ": "skura", "infinitiv": "skura", "presens": "skurar", "preteritum": "skurade", "supinum": "skurat", "group":"1", "translation": "to scrub/scour" },
  { "imperativ": "släng", "infinitiv": "slänga", "presens": "slänger", "preteritum": "slängde", "supinum": "slängt", "group":"2", "translation": "to throw away" },
  { "imperativ": "sluta", "infinitiv": "sluta", "presens": "slutar", "preteritum": "slutade", "supinum": "slutat", "group":"1", "translation": "to end/stop" },
  { "imperativ": "smaka", "infinitiv": "smaka", "presens": "smakar", "preteritum": "smakade", "supinum": "smakat", "group":"1", "translation": "to taste" },
  { "imperativ": "snöa", "infinitiv": "snöa", "presens": "snöar", "preteritum": "snöade", "supinum": "snöat", "group":"1", "translation": "to snow" },
  { "imperativ": "somna", "infinitiv": "somna", "presens": "somnar", "preteritum": "somnade", "supinum": "somnat", "group":"1", "translation": "to fall asleep" },
  { "imperativ": "sopa", "infinitiv": "sopa", "presens": "sopar", "preteritum": "sopade", "supinum": "sopat", "group":"1", "translation": "to sweep" },
  { "imperativ": "sov", "infinitiv": "sova", "presens": "sover", "preteritum": "sov", "supinum": "sovit", "group":"4a it-verb", "translation": "to sleep" },
  { "imperativ": "spara", "infinitiv": "spara", "presens": "sparar", "preteritum": "sparade", "supinum": "sparat", "group":"1", "translation": "to save" },
  { "imperativ": "spela", "infinitiv": "spela", "presens": "spelar", "preteritum": "spelade", "supinum": "spelat", "group":"1", "translation": "to play (games/music)" },
  { "imperativ": "spendera", "infinitiv": "spendera", "presens": "spenderar", "preteritum": "spenderade", "supinum": "spenderat", "group":"1", "translation": "to spend" },
  { "imperativ": "spill", "infinitiv": "spilla", "presens": "spiller", "preteritum": "spillde", "supinum": "spillt", "group":"2", "translation": "to spill" },
  { "imperativ": "spring", "infinitiv": "springa", "presens": "springer", "preteritum": "sprang", "supinum": "sprungit", "group":"4a it-verb", "translation": "to run" },
  { "imperativ": "stå", "infinitiv": "stå", "presens": "står", "preteritum": "stod", "supinum": "stått", "group":"4", "translation": "to stand" },
  { "imperativ": "städa", "infinitiv": "städa", "presens": "städar", "preteritum": "städade", "supinum": "städat", "group":"1", "translation": "to clean" },
  { "imperativ": "ställ", "infinitiv": "ställa", "presens": "ställer", "preteritum": "ställde", "supinum": "ställt", "group":"2", "translation": "to put/place" },
  { "imperativ": "stäm", "infinitiv": "stämma", "presens": "stämmer", "preteritum": "stämde", "supinum": "stämt", "group":"2", "translation": "to be correct" },
  { "imperativ": "stanna", "infinitiv": "stanna", "presens": "stannar", "preteritum": "stannade", "supinum": "stannat", "group":"1", "translation": "to stay/stop" },
  { "imperativ": "stek", "infinitiv": "steka", "presens": "steker", "preteritum": "stekte", "supinum": "stekt", "group":"2", "translation": "to fry" },
  { "imperativ": "stick", "infinitiv": "sticka", "presens": "sticker", "preteritum": "stack", "supinum": "stuckit", "group":"4a it-verb", "translation": "to leave/sting" },
  { "imperativ": "stryk", "infinitiv": "stryka", "presens": "stryker", "preteritum": "strök", "supinum": "strukit", "group":"4a it-verb", "translation": "to iron/stroke" },
  { "imperativ": "studera", "infinitiv": "studera", "presens": "studerar", "preteritum": "studerade", "supinum": "studerat", "group":"1", "translation": "to study" },
  { "imperativ": "surfa", "infinitiv": "surfa", "presens": "surfar", "preteritum": "surfade", "supinum": "surfat", "group":"1", "translation": "to surf" },
  { "imperativ": "svabba", "infinitiv": "svabba", "presens": "svabbar", "preteritum": "svabbade", "supinum": "svabbat", "group":"1", "translation": "to mop/swab" },
  { "imperativ": "sväng", "infinitiv": "svänga", "presens": "svänger", "preteritum": "svängde", "supinum": "svängt", "group":"2", "translation": "to turn" },
  { "imperativ": "svara", "infinitiv": "svara", "presens": "svarar", "preteritum": "svarade", "supinum": "svarat", "group":"1", "translation": "to answer" },
  { "imperativ": "svettas", "infinitiv": "svettas", "presens": "svettas", "preteritum": "svettades", "supinum": "svettats", "group":"1 (dep)", "translation": "to sweat" },
  { "imperativ": "sy", "infinitiv": "sy", "presens": "syr", "preteritum": "sydde", "supinum": "sytt", "group":"3", "translation": "to sew" },
  { "imperativ": "ta", "infinitiv": "ta", "presens": "tar", "preteritum": "tog", "supinum": "tagit", "group":"4a it-verb", "translation": "to take" },
  { "imperativ": "tänk", "infinitiv": "tänka", "presens": "tänker", "preteritum": "tänkte", "supinum": "tänkt", "group":"2", "translation": "to think" },
  { "imperativ": "testa", "infinitiv": "testa", "presens": "testar", "preteritum": "testade", "supinum": "testat", "group":"1", "translation": "to test" },
  { "imperativ": "tina", "infinitiv": "tina", "presens": "tinar", "preteritum": "tinade", "supinum": "tinat", "group":"1", "translation": "to thaw" },
  { "imperativ": "titta", "infinitiv": "titta", "presens": "tittar", "preteritum": "tittade", "supinum": "tittat", "group":"1", "translation": "to look" },
  { "imperativ": "torka", "infinitiv": "torka", "presens": "torkar", "preteritum": "torkade", "supinum": "torkat", "group":"1", "translation": "to dry/wipe" },
  { "imperativ": "träffa", "infinitiv": "träffa", "presens": "träffar", "preteritum": "träffade", "supinum": "träffat", "group":"1", "translation": "to meet" },
  { "imperativ": "träna", "infinitiv": "träna", "presens": "tränar", "preteritum": "tränade", "supinum": "tränat", "group":"1", "translation": "to train/exercise" },
  { "imperativ": "trivs", "infinitiv": "trivas", "presens": "trivs", "preteritum": "trivdes", "supinum": "trivts", "group":"2 (dep)", "translation": "to enjoy/be comfortable" },
  { "imperativ": "tro", "infinitiv": "tro", "presens": "tror", "preteritum": "trodde", "supinum": "trott", "group":"3", "translation": "to believe" },
  { "imperativ": "tvätta", "infinitiv": "tvätta", "presens": "tvättar", "preteritum": "tvättade", "supinum": "tvättat", "group":"1", "translation": "to wash" },
  { "imperativ": "tyck", "infinitiv": "tycka", "presens": "tycker", "preteritum": "tyckte", "supinum": "tyckt", "group":"2", "translation": "to think/opinion" },
  { "imperativ": "umgås", "infinitiv": "umgås", "presens": "umgås", "preteritum": "umgicks", "supinum": "umgåtts", "group":"4 (dep)", "translation": "to socialize" },
  { "imperativ": "undvik", "infinitiv": "undvika", "presens": "undviker", "preteritum": "undvek", "supinum": "undvikit", "group":"4a it-verb", "translation": "to avoid" },
  { "imperativ": "ursäkta", "infinitiv": "ursäkta", "presens": "ursäktar", "preteritum": "ursäktade", "supinum": "ursäktat", "group":"1", "translation": "to excuse" },
  { "imperativ": "utvärdera", "infinitiv": "utvärdera", "presens": "utvärderar", "preteritum": "utvärderade", "supinum": "utvärderat", "group":"1", "translation": "to evaluate" },
  { "imperativ": "väck", "infinitiv": "väcka", "presens": "väcker", "preteritum": "väckte", "supinum": "väckt", "group":"2", "translation": "to wake someone up" },
  { "imperativ": "vakna", "infinitiv": "vakna", "presens": "vaknar", "preteritum": "vaknade", "supinum": "vaknat", "group":"1", "translation": "to wake up" },
  { "imperativ": "välj", "infinitiv": "välja", "presens": "väljer", "preteritum": "valde", "supinum": "valt", "group":"2", "translation": "to choose" },
  { "imperativ": "vandra", "infinitiv": "vandra", "presens": "vandrar", "preteritum": "vandrade", "supinum": "vandrat", "group":"1", "translation": "to hike" },
  { "imperativ": "vänta", "infinitiv": "vänta", "presens": "väntar", "preteritum": "väntade", "supinum": "väntat", "group":"1", "translation": "to wait" },
  { "imperativ": "var", "infinitiv": "vara", "presens": "är", "preteritum": "var", "supinum": "varit", "group":"4 (irr)", "translation": "to be" },
  { "imperativ": "vattna", "infinitiv": "vattna", "presens": "vattnar", "preteritum": "vattnade", "supinum": "vattnat", "group":"1", "translation": "to water" },
  { "imperativ": "väx", "infinitiv": "växa", "presens": "växer", "preteritum": "växte", "supinum": "växt", "group":"2", "translation": "to grow" },
  { "imperativ": "verka", "infinitiv": "verka", "presens": "verkar", "preteritum": "verkade", "supinum": "verkat", "group":"1", "translation": "to seem" },
  { "imperativ": "vet", "infinitiv": "veta", "presens": "vet", "preteritum": "visste", "supinum": "vetat", "group":"4 (irr)", "translation": "to know (info)" },
  { "imperativ": "vik", "infinitiv": "vika", "presens": "viker", "preteritum": "vek", "supinum": "vikit", "group":"4a it-verb", "translation": "to fold" },
  { "imperativ": "vila", "infinitiv": "vila", "presens": "vilar", "preteritum": "vilade", "supinum": "vilat", "group":"1", "translation": "to rest" },
  { "imperativ": "-", "infinitiv": "vilja", "presens": "vill", "preteritum": "ville", "supinum": "velat", "group":"4 (modal)", "translation": "to want" },
  { "imperativ": "vrid", "infinitiv": "vrida", "presens": "vrider", "preteritum": "vred", "supinum": "vridit", "group":"4a it-verb", "translation": "to turn/twist" },
  { "imperativ": "se", "infinitiv": "se", "presens": "ser", "preteritum": "såg", "supinum": "sett", "group":"4", "translation": "to see" }


];