/* ================================================================
   DATA: KONSUMTION (CONSUMPTION)
   ================================================================ */

const nounConsumption_Data = [
  { "article": "en", "singularOb": "medlem", "singularBe": "medlemmen", "pluralOb": "medlemmar", "pluralBe": "medlemmarna", "group": "2", "translation": "member" },
  { "article": "en", "singularOb": "grej", "singularBe": "grejen", "pluralOb": "grejer", "pluralBe": "grejerna", "group": "3", "translation": "thing / gadget" },
  { "article": "en", "singularOb": "garderob", "singularBe": "garderoben", "pluralOb": "garderober", "pluralBe": "garderoberna", "group": "3", "translation": "wardrobe" },
  { "article": "ett", "singularOb": "köp", "singularBe": "köpet", "pluralOb": "köp", "pluralBe": "köpen", "group": "5", "translation": "purchase" },
  { "article": "ett", "singularOb": "pris", "singularBe": "priset", "pluralOb": "priser", "pluralBe": "priserna", "group": "3*", "translation": "price" },
  { "article": "en", "singularOb": "kampanj", "singularBe": "kampanjen", "pluralOb": "kampanjer", "pluralBe": "kampanjerna", "group": "3", "translation": "campaign" },
  { "article": "ett", "singularOb": "erbjudande", "singularBe": "erbjudandet", "pluralOb": "erbjudanden", "pluralBe": "erbjudandena", "group": "4", "translation": "offer" },
  { "article": "ett", "singularOb": "extrapris", "singularBe": "extrapriset", "pluralOb": "extrapriser", "pluralBe": "extrapriserna", "group": "3", "translation": "special price / sale price" },
  { "article": "en", "singularOb": "rabatt", "singularBe": "rabatten", "pluralOb": "rabatter", "pluralBe": "rabatterna", "group": "3", "translation": "discount" },
  { "article": "en", "singularOb": "rea", "singularBe": "rean", "pluralOb": "reor", "pluralBe": "reorna", "group": "1", "translation": "sale" },
  { "article": "en", "singularOb": "kod", "singularBe": "koden", "pluralOb": "koder", "pluralBe": "koderna", "group": "3", "translation": "code" },
  { "article": "ett", "singularOb": "nyhetsbrev", "singularBe": "nyhetsbrevet", "pluralOb": "nyhetsbrev", "pluralBe": "nyhetsbreven", "group": "5", "translation": "newsletter" },
  { "article": "en", "singularOb": "miljö", "singularBe": "miljön", "pluralOb": "miljöer", "pluralBe": "miljöerna", "group": "3", "translation": "environment" },
  { "article": "en", "singularOb": "ekonomi", "singularBe": "ekonomin", "pluralOb": "ekonomier", "pluralBe": "ekonomierna", "group": "3", "translation": "economy / finances" },
  { "article": "en", "singularOb": "vana", "singularBe": "vanan", "pluralOb": "vanor", "pluralBe": "vanorna", "group": "1", "translation": "habit" },
  { "article": "en", "singularOb": "butik", "singularBe": "butiken", "pluralOb": "butiker", "pluralBe": "butikerna", "group": "3", "translation": "shop / store" },
  { "article": "en", "singularOb": "affär", "singularBe": "affären", "pluralOb": "affärer", "pluralBe": "affärerna", "group": "3", "translation": "shop / business" },
  { "article": "ett", "singularOb": "kvitto", "singularBe": "kvittot", "pluralOb": "kvitton", "pluralBe": "kvittona", "group": "4", "translation": "receipt" },
  { "article": "en", "singularOb": "kassör", "singularBe": "kassören", "pluralOb": "kassörer", "pluralBe": "kassörerna", "group": "3", "translation": "cashier" },
  { "article": "en", "singularOb": "personal", "singularBe": "personalen", "pluralOb": "personal", "pluralBe": "personalen", "group": "5", "translation": "staff" },
  { "article": "en", "singularOb": "påse", "singularBe": "påsen", "pluralOb": "påsar", "pluralBe": "påsarna", "group": "2", "translation": "bag (plastic/paper)" },
  { "article": "en", "singularOb": "kasse", "singularBe": "kassen", "pluralOb": "kassar", "pluralBe": "kassarna", "group": "2", "translation": "shopping bag" },
  { "article": "en", "singularOb": "kassa", "singularBe": "kassan", "pluralOb": "kassor", "pluralBe": "kassorna", "group": "1", "translation": "checkout / cash desk" },
  { "article": "ett", "singularOb": "kort", "singularBe": "kortet", "pluralOb": "kort", "pluralBe": "korten", "group": "5", "translation": "card" },
  { "article": "en", "singularOb": "sedel", "singularBe": "sedeln", "pluralOb": "sedlar", "pluralBe": "sedlarna", "group": "2", "translation": "banknote / bill" },
  { "article": "ett", "singularOb": "mynt", "singularBe": "myntet", "pluralOb": "mynt", "pluralBe": "mynten", "group": "5", "translation": "coin" },
  { "article": "en", "singularOb": "vara", "singularBe": "varan", "pluralOb": "varor", "pluralBe": "varorna", "group": "1", "translation": "product / commodity" },
  { "article": "en", "singularOb": "artikel", "singularBe": "artikeln", "pluralOb": "artiklar", "pluralBe": "artiklarna", "group": "2", "translation": "article / item" },
  { "article": "en", "singularOb": "produkt", "singularBe": "produkten", "pluralOb": "produkter", "pluralBe": "produkterna", "group": "3", "translation": "product" },
  { "article": "ett", "singularOb": "hushåll", "singularBe": "hushållet", "pluralOb": "hushåll", "pluralBe": "hushållen", "group": "5", "translation": "household" },
  { "article": "en", "singularOb": "tjänst", "singularBe": "tjänsten", "pluralOb": "tjänster", "pluralBe": "tjänsterna", "group": "3", "translation": "service" },
  { "article": "en", "singularOb": "recension", "singularBe": "recensionen", "pluralOb": "recensioner", "pluralBe": "recensionerna", "group": "3", "translation": "review" },
  { "article": "-", "singularOb": "legitimation", "singularBe": "legitimationen", "pluralOb": "legitimationer", "pluralBe": "legitimationerna", "group": "3", "translation": "ID / identification" },
  { "article": "en", "singularOb": "lista", "singularBe": "listan", "pluralOb": "listor", "pluralBe": "listorna", "group": "1", "translation": "list" },
  { "article": "ett", "singularOb": "inköp", "singularBe": "inköpet", "pluralOb": "inköp", "pluralBe": "inköpen", "group": "5", "translation": "purchase / shopping" },
  { "article": "en", "singularOb": "inköpslista", "singularBe": "inköpslistan", "pluralOb": "inköpslistor", "pluralBe": "inköpslistorna", "group": "1", "translation": "shopping list" },
  { "article": "en", "singularOb": "reklam", "singularBe": "reklamen", "pluralOb": "reklamer", "pluralBe": "reklamerna", "group": "3", "translation": "advertisement" },
  { "article": "ett", "singularOb": "reklamblad", "singularBe": "reklambladet", "pluralOb": "reklamblad", "pluralBe": "reklambladen", "group": "5", "translation": "flyer / leaflet" },
  { "article": "ett", "singularOb": "presentkort", "singularBe": "presentkortet", "pluralOb": "presentkort", "pluralBe": "presentkorten", "group": "5", "translation": "gift card" },
  { "article": "ett", "singularOb": "abonnemang", "singularBe": "abonnemanget", "pluralOb": "abonnemang", "pluralBe": "abonnemangen", "group": "5", "translation": "subscription" },
  { "article": "en", "singularOb": "avgift", "singularBe": "avgiften", "pluralOb": "avgifter", "pluralBe": "avgifterna", "group": "3", "translation": "fee/charge" },
  { "article": "ett", "singularOb": "belopp", "singularBe": "beloppet", "pluralOb": "belopp", "pluralBe": "beloppen", "group": "5", "translation": "amount" },
  { "article": "ett", "singularOb": "bidrag", "singularBe": "bidraget", "pluralOb": "bidrag", "pluralBe": "bidragen", "group": "5", "translation": "grant/contribution" },
  { "article": "en", "singularOb": "budget", "singularBe": "budgeten", "pluralOb": "budgetar", "pluralBe": "budgetarna", "group": "2", "translation": "budget" },
  { "article": "en", "singularOb": "frakt", "singularBe": "frakten", "pluralOb": "frakter", "pluralBe": "frakterna", "group": "3", "translation": "shipping/freight" },
  { "article": "en", "singularOb": "inkomst", "singularBe": "inkomsten", "pluralOb": "inkomster", "pluralBe": "inkomsterna", "group": "3", "translation": "income" },
  { "article": "ett", "singularOb": "konto", "singularBe": "kontot", "pluralOb": "konton", "pluralBe": "kontona", "group": "4", "translation": "account" },
  { "article": "en", "singularOb": "kostnad", "singularBe": "kostnaden", "pluralOb": "kostnader", "pluralBe": "kostnaderna", "group": "3", "translation": "cost" },
  { "article": "en", "singularOb": "kund", "singularBe": "kunden", "pluralOb": "kunder", "pluralBe": "kunderna", "group": "3", "translation": "customer" },
  { "article": "en", "singularOb": "utgift", "singularBe": "utgiften", "pluralOb": "utgifter", "pluralBe": "utgifterna", "group": "3", "translation": "expense" },
  { "article": "ett", "singularOb": "lån", "singularBe": "lånet", "pluralOb": "lån", "pluralBe": "lånen", "group": "5", "translation": "loan" },
  { "article": "en", "singularOb": "lön", "singularBe": "lönen", "pluralOb": "löner", "pluralBe": "lönerna", "group": "3", "translation": "salary" },
  { "article": "en", "singularOb": "skatt", "singularBe": "skatten", "pluralOb": "skatter", "pluralBe": "skatterna", "group": "3", "translation": "tax" },
  { "article": "ett", "singularOb": "misstag", "singularBe": "misstaget", "pluralOb": "misstag", "pluralBe": "misstagen", "group": "5", "translation": "mistake" },
  { "article": "en", "singularOb": "retur", "singularBe": "returen", "pluralOb": "returer", "pluralBe": "returerna", "group": "3", "translation": "return" },
  { "article": "ett", "singularOb": "råd", "singularBe": "rådet", "pluralOb": "råd", "pluralBe": "råden", "group": "5", "translation": "advice" },
  { "article": "en", "singularOb": "plånbok", "singularBe": "plånboken", "pluralOb": "plånböcker", "pluralBe": "plånböckerna", "group": "3", "translation": "wallet" }
];